haskell/haskell-ide-engine

docs/Tools.md
list of tools: short descriptions + links
you can see the new file here: https://github.com/rvion/haskell-ide-engine/blob/update-list-of-existing-tools/docs/Tools.md
=> (RFC) [list of tools] add more tools, add links, add short descriptions, group tools

elisp/haskell-ide-engine.el, elisp/tests/haskell-ide-engine-tests.el, src/Haskell/Ide/Engine/Transport/JsonStdio.hs
=> Improve wire protocol

app/MainHie.hs, src/Haskell/Ide/Engine/Options.hs, src/Haskell/Ide/Engine/Transport/JsonHttp.hs
I'm not super happy with "web" as an option name but I couldn't come up with anything better.
=> Make web interface optional and port configurable

haskell-ide-example-plugin2/Haskell/Ide/ExamplePlugin2.hs, haskell-ide-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, haskell-ide-plugin-ghcmod/Haskell/Ide/GhcModPlugin.hs, haskell-ide-plugin-hare/Haskell/Ide/HaRePlugin.hs, src/Haskell/Ide/Engine/BasePlugin.hs, src/Haskell/Ide/Engine/Console.hs, src/Haskell/Ide/Engine/Transport/JsonHttp.hs, src/Haskell/Ide/Engine/Transport/JsonStdio.hs, test/GhcModPluginSpec.hs, test/HaRePluginSpec.hs, test/JsonStdioSpec.hs
=> Remove Context, simplifying IdeRequest

haskell-ide-engine.cabal, src/Haskell/Ide/Engine/Console.hs
Add some basic help, and parse parameters according to the `CommandDescription` so that the types line up when passed to the dispatcher.
=> Improve console

elisp/haskell-ide-engine.el, elisp/tests/haskell-ide-engine-tests.el, src/Haskell/Ide/Engine/BasePlugin.hs
Add some tests for some commands, fixing them along the way.
=> Implement testing framework for Emacs (plus some fixes)

.gitignore, haskell-ide-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, haskell-ide-plugin-hare/Haskell/Ide/HaRePlugin.hs, test/HaRePluginSpec.hs, test/testdata/HaReCase.hs, test/testdata/HaReDemote.hs, test/testdata/HaReMoveDef.hs
=> Add the rest of the commands to HaRe plugin

haskell-ide-engine.cabal, haskell-ide-plugin-ghcmod/Haskell/Ide/GhcModPlugin.hs, haskell-ide-plugin-ghcmod/haskell-ide-plugin-ghcmod.cabal, test/GhcModPluginSpec.hs, test/HaRePluginSpec.hs, test/testdata/FileWithWarning.hs
Adding some more ghc-mod commands
=> Ghcmod commands

elisp/tests/haskell-ide-engine-tests.el, haskell-ide-engine.cabal, haskell-ide-example-plugin2/Haskell/Ide/ExamplePlugin2.hs, haskell-ide-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, haskell-ide-plugin-api/Haskell/Ide/Engine/PluginUtils.hs, haskell-ide-plugin-api/haskell-ide-plugin-api.cabal, haskell-ide-plugin-ghcmod/Haskell/Ide/GhcModPlugin.hs, haskell-ide-plugin-hare/Haskell/Ide/HaRePlugin.hs, src/Haskell/Ide/Engine/BasePlugin.hs, src/Haskell/Ide/Engine/Dispatcher.hs, src/Haskell/Ide/Engine/Transport/JsonHttp.hs, src/Haskell/Ide/Engine/Transport/JsonStdio.hs, src/Haskell/Ide/Engine/Types.hs, test/DispatcherSpec.hs, test/GhcModPluginSpec.hs, test/HaRePluginSpec.hs
This is the first draft of typing the responses from commands. We have a typeclass that can serialize to Object. In dispatcher we actually convert to Object which means the dispatcher at the end doesn't have to deal with all these types. I haven't changed the JSON serialization, and of course may have added more infelicities mapping from String/Text to Object. We probably need to lay down the format we want for the JSON.
=> Typed responses

elisp/haskell-ide-engine.el
Supposed to be used in conjunction with #59.
=> Implement STX

elisp/haskell-ide-engine.el
=> [WIP] Initial stab at hie-mode

hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, hie-ghc-mod/hie-ghc-mod.cabal
Sets current directory for ghc-mod using rootInfo, fixes #87
=> Ghc mod dir

hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, src/Haskell/Ide/Engine/BasePlugin.hs
Here’s a less intrusive approach which accomplishes the same thing.
=> Add plugin name to commandDetail response

hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, test/GhcModPluginSpec.hs, test/JsonSpec.hs
discussed with @alanz  on IRC: make position a clearer object in JSON, parse the type info string from ghc-mod
=> Json enhancements

elisp/haskell-ide-engine.el
The fact that this uses `eval` is kinda ugly, but we can’t get away with a macro here, since that would expanded when the function is defined and not when it’s applied, so we can’t use any local parameters here which makes it sadly useless for this purpose.
=> Create elisp functions for all commands

docs/Tools.md
=> docs: mention apply-refact, hsimport, haskdogs

hie-example-plugin2/Haskell/Ide/ExamplePlugin2.hs, hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, hie-hare/Haskell/Ide/HaRePlugin.hs, hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, src/Haskell/Ide/Engine/BasePlugin.hs, test/DispatcherSpec.hs, test/HaRePluginSpec.hs, test/JsonSpec.hs
The JSON for parameters really leaked our internal structure without being understandable. Changed it to something saner in my opinion.
=> nicer parameters and command return type

haskell-ide-engine.cabal, hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, hie-hare/Haskell/Ide/HaRePlugin.hs, hie-hare/hie-hare.cabal, hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs, hie-plugin-api/Haskell/Ide/Engine/SemanticTypes.hs, hie-plugin-api/hie-plugin-api.cabal, stack.yaml, test/GhcModPluginSpec.hs, test/HaRePluginSpec.hs, test/JsonSpec.hs
I have now created a separate file for the types that are expected to be
understood by an IDE.
=> Bring in a diff type, and introduce semantic types

.travis.yml, Makefile, hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, hie-plugin-api/Haskell/Ide/Engine/Monad.hs, hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, hie-plugin-api/hie-plugin-api.cabal, stack.yaml, test/GhcModPluginSpec.hs
Simplify IdeM so that ghc-mod session caching can be used.
This provides a significant performance boost.
Closes #127
=> Ghc mod session

hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs, hie-plugin-api/Haskell/Ide/Engine/SemanticTypes.hs, test/ApplyRefactPluginSpec.hs, test/HaRePluginSpec.hs
=> Change HieDiff to use a patch format

LICENSE, README.md, haskell-ide-engine.cabal
I'd like to do some work on this project, but while delving into it I found I'm probably not up to the level of Haskell experience to be of any use within the limited time I have available. I did notice some thing in on the textual side that I could fix, so I did.
=> Just some textual improvements

app/MainHie.hs, haskell-ide-engine.cabal, hie-base/Haskell/Ide/Engine/SemanticTypes.hs, hie-ghc-tree/Haskell/Ide/GhcTreePlugin.hs, hie-ghc-tree/Setup.hs, hie-ghc-tree/hie-ghc-tree.cabal, stack.yaml, stack_test.yaml, test/GhcTreePluginSpec.hs
Little plugin around the newly created ghc-dump-tree library to get the full AST
=> Ghc-dump-tree plugin

elisp/Cask, elisp/hie.el, elisp/tests/hie-test.el, stack.yaml
There is more work to be done here, but it already works better than the current state and I prefer iterating in smaller steps.
=> Support multiple sessions in emacs

hie-docs-generator/hie-docs-generator.cabal, hie-docs-generator/src/Main.hs
pcre-heavy doesn’t work (out of the box) on windows
=> Use regex-applicative instead of pcre-heavy

hie-docs-generator/src/Main.hs
A naive attempt making commands like "hie-docs-generator
--prefix="~/hiedocs"" work as intended. Addresses #199
=> Handle ~ path naively

elisp/hie.el
Without this I get an error at load time.
=> Require buttercup

haskell-ide-engine.cabal, src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack.yaml
Return ghc-mod diagnostics as well as hlint ones
=> Ghc mod diagnostics

.travis.yml, circle.yml, haskell-ide-engine.cabal, src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack.yaml
And accept `text` params in `workspace/executeCommand` parameters
=> Adapt to hskell-lsp VFS

haskell-ide-engine.cabal, src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack.yaml, test/testdata/stack.yaml
Fix circleci build by updating the stackage nightly to one including hoogle 5.0.12
There is something odd about the circleci caching.
=> Update Stackage nightly

stack.yaml, test/Functional.hs, test/testdata/gototest/stack.yaml, test/testdata/stack.yaml
Which fixes the default config file problem.
=> Update to hlint 2.0.9

hie-apply-refact/Haskell/Ide/ApplyRefactPlugin.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack.yaml, test/ApplyRefactPluginSpec.hs
HaRe isn't working on mapped files right now- it fails with unexpected error parsing $file.
ghc-mod and hlint are working(as far as I've tested).
=> Integrate VFS into hie

haskell-ide-engine.cabal, hie-apply-refact/Haskell/Ide/ApplyRefactPlugin.hs, hie-brittany/Haskell/Ide/BrittanyPlugin.hs, hie-brittany/Setup.hs, hie-brittany/hie-brittany.cabal, hie-hare/Haskell/Ide/HaRePlugin.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack.yaml
Range formatting doesn't take into account pragmas yet, so often fails.
~~Also, we don't take into account client supplied Formatting Options yet.~~
Closes #215 and lspitzner/brittany#5
=> Brittany plugin and support for textDocument/formatting, textDocument/rangeFormatting

app/MainHie.hs, haskell-ide-engine.cabal, hie-apply-refact/Haskell/Ide/ApplyRefactPlugin.hs, hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, hie-ghc-mod/hie-ghc-mod.cabal, hie-hare/Haskell/Ide/HaRePlugin.hs, hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs, hie-plugin-api/hie-plugin-api.cabal, src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack.yaml, test/ApplyRefactPluginSpec.hs, test/DispatcherSpec.hs, test/ExamplePluginAsyncSpec.hs, test/ExtensibleStateSpec.hs, test/Functional.hs, test/GhcModPluginSpec.hs, test/GhcTreePluginSpec.hs, test/HaRePluginSpec.hs, test/HooglePluginSpec.hs
=> Caching of typechecked module and cached findDef, typeAt

hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, hie-hare/Haskell/Ide/HaRePlugin.hs, hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack.yaml
* Always map files
* Move loading/hook logic into HIE from HaRe and clean it up
* improvements to document highlight
* Fix CPP includes for mapped files
* improvements to hover request
* various bug fixes
* report compile errors that don't have a SrcSpan to users via showMessage. (Previously some were logged in the debug log and some were reported as IdeErrors)
=> Many improvements

hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, hie-hare/Haskell/Ide/HaRePlugin.hs, hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs, hie-plugin-api/hie-plugin-api.cabal, src/Haskell/Ide/Engine/Transport/LspStdio.hs
Improvements to hover and highlighting. Record Puns and Wildcards are now handled and work with hovering and highlighting.
=> Using fingertree to find all symbols at point.

haskell-ide-engine.cabal
Since I found this really useful on GHC 8.0.1
=> Add -Wredundant-constraints

haskell-ide-engine.cabal, hie-plugin-api/Haskell/Ide/Engine/MonadFunctions.hs, hie-plugin-api/hie-plugin-api.cabal, test/Functional.hs, test/Main.hs, test/TestUtils.hs
=> Fix merge error, use hslogger only

src/Haskell/Ide/Engine/Transport/LspStdio.hs
I went ahead and made the change that I mentioned here https://github.com/haskell/haskell-ide-engine/issues/285#issuecomment-322363992.
=> Log hoogle db location instead of displaying a popup

haskell-ide-engine.cabal, src/Haskell/Ide/Engine/Transport/JsonStdio.hs, stack.yaml
also cleanup stack.yaml
Responses are also separated by \STX now.
=> Fix JSONStdio

hie-hare/Haskell/Ide/HaRePlugin.hs
Per #302, this PR uses record syntax in `HaRePlugin` to insulate a bit against changes to ghc datatypes.
In particular, ghc 8.2.1 adds fixity fields to most of these constructors, so not relying on the # and ordering of them allows us to support both 8 & 8.2 without e.g. `CPP`.
=> Destructure ghc types with record syntax.

app/MainHie.hs, hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, hie-hare/Haskell/Ide/HaRePlugin.hs, hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs, src/Haskell/Ide/Engine/Dispatcher.hs, src/Haskell/Ide/Engine/Transport/JsonStdio.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack.yaml
Should fix #279,  https://github.com/alanz/vscode-hie-server/issues/10 (both confirmed) and #299 (not yet confirmed)
=> Use latest ghc-mod to fix mapped files issue

README.md, stack.yaml
=> Support installation via Nix

stack-8.2.1.yaml, stack.yaml
Closes https://github.com/haskell/haskell-ide-engine/issues/325
=> Fix dangling commits in stack.yaml

.gitignore, circle.yml, haskell-ide-engine.cabal, hie-build-plugin/Haskell/Ide/BuildPlugin.hs, hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, hie-haddock/Haskell/Ide/HaddockPlugin.hs, hie-haddock/Setup.hs, hie-haddock/hie-haddock.cabal, hie-hare/Haskell/Ide/HaRePlugin.hs, hie-plugin-api/Haskell/Ide/Engine/LocMap.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack-8.2.1.yaml, stack.yaml, test/TestUtils.hs
This is a rebase/merge of the branch @wz1000 was working on, together with updates for use with current (under development) ghc-mod / cabal-helper and GHC 8.2.1
@wz1000 please take a look, particularly at the documentation stuff, which you said needed more work.
=> GHC 8.2.1 @wz1000 additions

src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack-8.2.1.yaml, stack.yaml
Process the `'workspace/didChangeConfiguration` in `haskell-lsp`, and make it available via `LspFuncs` in hie.
This currently implements a flag to enable hlint, and a setting for the number of diagnostics to return.
Integrated into https://github.com/alanz/vscode-hie-server/tree/settings
=> Manage client settings

hie-hare/Haskell/Ide/HaRePlugin.hs
Current behavior: when for some reason `HIE` is unable to find a definition for a given symbol to navigate to, the error is returned to the client:
`hare:findDef:<no location found>`.
This includes all the symbols that are defined outside of the current project (`base` and libraries)
I find that error message unhelpful and noisy. There is no way client can compensate for it and no way user can benefit from it or fix it. 
With the suggested fix `HaRe` will return an empty successful response if it can't find a location to navigate to. `VSCode` deals with it correctly by not showing the possibility to jump to the definition.  
I suggest to use `?w=1` in github review (https://github.com/haskell/haskell-ide-engine/pull/335/files?w=1) to see the change without an indentation noise.
=> Don't propagate error if no definition is found

stack-8.2.1.yaml, stack.yaml
Which cases issues for OS/X builds, apparently
=> Update for ghc-mod without shebangs in Setup.hs

README.md
=> Add Sublime Text to README

hie-hare/Haskell/Ide/HaRePlugin.hs, src/Haskell/Ide/Engine/Dispatcher.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, test/DispatcherSpec.hs, test/Functional.hs
To speed things up.
@wz1000 I want to bring this in now, as it has a big responsiveness impact.
You can then rework the rest as per our new architecture discussion.
Note: The fancy hoogle lookup has had to be lost in the process. Tradeoff.
=> Only give a hover result if we already have the cached module

haskell-ide-engine.cabal, hie-build-plugin/Haskell/Ide/BuildPlugin.hs, hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, src/Haskell/Ide/Engine/Dispatcher.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, stack-8.2.1.yaml, stack.yaml
Use `haskell-lsp-0.2.0.0` from the latest stackage nightly. For the GHC 8.2.1 build
=> Haskell lsp nightly

stack-8.2.1.yaml, stack.yaml, test/ApplyRefactPluginSpec.hs, test/testdata/.hlint.yaml, test/testdata/HlintPragma.hs
=> Use updated hlint, respects config files

hie-apply-refact/Haskell/Ide/ApplyRefactPlugin.hs, test/ApplyRefactPluginSpec.hs, test/Functional.hs
=> Use severity:3 (info) for hlint errors and warnings

src/Haskell/Ide/Engine/Transport/LspStdio.hs
This is a temporary workaround to prevent client crashes.
See #370
=> Send back an empty response to "textDocument/references"

src/Haskell/Ide/Engine/Transport/LspStdio.hs
=> Ignore "workspace/didChangeWatchedFiles" notification.

README.md
This PR add installation instructions for ArchLinux users.
=> ArchLinux User Repository package

test/TestUtils.hs
=> Use LTS-9.14 snapshot for 8.0.2 tests

haskell-ide-engine.cabal, hie-apply-refact/Haskell/Ide/ApplyRefactPlugin.hs, hie-apply-refact/hie-apply-refact.cabal, hie-base/Haskell/Ide/Engine/PluginTypes.hs, hie-build-plugin/hie-build-plugin.cabal, hie-haddock/Haskell/Ide/HaddockPlugin.hs, hie-hare/Haskell/Ide/HaRePlugin.hs, hie-hare/hie-hare.cabal, hie-plugin-api/Haskell/Ide/Engine/IdeFunctions.hs, hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs, src/Haskell/Ide/Engine/Dispatcher.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, src/Haskell/Ide/Engine/Types.hs, stack-8.0.2.yaml, stack-8.2.1.yaml, stack.yaml
=> Fix -Werror and make sure pedantic applies to all

README.md
=> specify that stack 1.6.1 is required

hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs, test/GhcModPluginSpec.hs
=> Undelete type cmd

app/MainHie.hs, src/Haskell/Ide/Engine/Options.hs, src/Haskell/Ide/Engine/Plugin/Base.hs
Remove the ones that are not used, and add an ability to set the EKG port for
its server.
=> Rationalise command line arguments

hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs, hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs, hie-plugin-api/Haskell/Ide/Engine/MonadTypes.hs, hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs, hie-plugin-api/hie-plugin-api.cabal
Just some preliminary rearrangements for the completion refactoring I'm working on. No behavioral change, but it's big enough that I want to get it in sooner than later.
=> Add typeclass constraints - rearrange modules to resolve circular dependencies

stack-8.0.2.yaml, stack-8.2.1.yaml, stack.yaml
Have not tested this at all locally. Trusting the CI.
=> Switch to brittany-0.10.0.0

.circleci/config.yml
Give each compiler its own cache key
=> Tweak circleci caching

.circleci/config.yml
Hi @alanz 
I see that you are working on CCI 2.0. Have a look, maybe you'll like this config?
=> DRY CCI 2.0

src/Haskell/Ide/Engine/Plugin/Brittany.hs
- Use latest `Brittany`
- Respect `Brittany`'s config files (both global and local)
With this change users can update their "global" Brittany's config files (`~/.config/brittany/config.yaml`) and/or "local" (project level) config files (`brittany.yaml`) and this configuration will be taken into account.
=> Read Brittany configuration

hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs, src/Haskell/Ide/Engine/Plugin/GhcMod.hs
Should fix https://github.com/haskell/haskell-ide-engine/issues/551 and https://github.com/alanz/vscode-hie-server/issues/80
=> Start canonicalizing mapped files again

src/Haskell/Ide/Engine/Transport/LspStdio.hs
=> Log the GHC version on startup

app/MainHie.hs, haskell-ide-engine.cabal, src/Haskell/Ide/Engine/Plugin/Brittany.hs, test/BrittanySpec.hs, test/testdata/BrittanyCRLF.hs, test/testdata/BrittanyLF.hs
Should fix #561, same thing as #525
=> Fix format selection adding an extra newline

Makefile
forward slash for path separators
=> Fix makefile for Linux use

stack.yaml
=> Use working haddock libraries for GHC 8.4.2

Makefile
=> Fix local bin path eval for OSX

Makefile
It's unbuildable due to missing stack-8.0.2.yaml file anyway
=> Remove 8.0.2 targets from Makefile

src/Haskell/Ide/Engine/Plugin/HieExtras.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, test/HaRePluginSpec.hs
Can anyone try this out and confirm that findDef doesn't fail on any cases it handled before this commit?
=> Remove dead code from findDef and make it async

README.md
=> Document useHieWrapper for VSCode in README

src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, src/Haskell/Ide/Engine/Types.hs, test/ApplyRefactPluginSpec.hs
And also filters out the hlint hints that do not have refactorings.
Or one of them anyway, Eta reduce.  But more can be added easily.
=> CodeAction request is now faster

docs/Dispatch.md
Begin documenting the new architecture. Addresses #596
=> Document dispatch

.circleci/config.yml, Makefile, README.md, stack-8.4.2.yaml, test/TestUtils.hs
Supersedes https://github.com/haskell/haskell-ide-engine/pull/608
=> Add support for GHC 8.4.3

docs/Architecture.md, hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs, hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs, hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs, src/Haskell/Ide/Engine/Dispatcher.hs, src/Haskell/Ide/Engine/Plugin/GhcMod.hs, src/Haskell/Ide/Engine/Plugin/HieExtras.hs, src/Haskell/Ide/Engine/Transport/JsonStdio.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, test/Functional.hs, test/testdata/FuncTestFail.hs
And return empty lists rather than errors for
- find definition
- references
=> Manage deferred requests when module loading fails

stack-8.2.1.yaml, stack-8.2.2.yaml, stack-8.4.2.yaml, stack.yaml
=> Use yi-rope-0.11 from hackage

app/HieWrapper.hs, cabal.project, haskell-ide-engine.cabal
Haskell version of the `hie-wrapper.sh` script in https://github.com/alanz/vscode-hie-server
This is now a cross-platform executable, and part of hie.
So it can be used by all clients.
=> Hie wrapper

README.md
=> Add config options to readme

haskell-ide-engine.cabal, stack-8.2.1.yaml, stack-8.2.2.yaml, stack-8.4.2.yaml, stack.yaml
And bump to current resolvers.
=> Update to newer cabal-helper

app/HieWrapper.hs, app/MainHie.hs, src/Haskell/Ide/Engine/Plugin/Base.hs
=> Fallback to using plain GHC if we can't find stack when checking version

app/HieWrapper.hs
This pull request fixes #660 by adding the required extension on windows.
=> Fixes #660 by adding windows specific extension

Makefile
Will be useful for making a brew formula where we can list icu4c as a
dependency there
=> Add version of icu-macos-fix with no brew install

.gitmodules
GitLab is undergoing maintenance at the moment
=> Change HaRe submodule remote to github

.circleci/config.yml, haskell-ide-engine.cabal
=> Add workaround for stack internal library bug

cabal.project
Perhaps we should include a circle ci test for new-build too.
Or run it on travis, using the haskell-ci scripts
=> Update cabal.project submodules for current master

Changelog.md, haskell-ide-engine.cabal, hie-plugin-api/hie-plugin-api.cabal
=> Bump to 0.2.2.0

hie-plugin-api/hie-plugin-api.cabal
=> Add bounds to haskell-lsp in hie-plugin-api

README.md, appveyor.yml
No tests for now, they're pretty badly broken.
Closes #704
=> Add appveyor CI build for windows

app/MainHie.hs, hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs, src/Haskell/Ide/Engine/LSP/CodeActions.hs, src/Haskell/Ide/Engine/LSP/Reactor.hs, src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs, src/Haskell/Ide/Engine/Plugin/Base.hs, src/Haskell/Ide/Engine/Plugin/Brittany.hs, src/Haskell/Ide/Engine/Plugin/Build.hs, src/Haskell/Ide/Engine/Plugin/Example2.hs, src/Haskell/Ide/Engine/Plugin/GhcMod.hs, src/Haskell/Ide/Engine/Plugin/HaRe.hs, src/Haskell/Ide/Engine/Plugin/Haddock.hs, src/Haskell/Ide/Engine/Plugin/Hoogle.hs, src/Haskell/Ide/Engine/Plugin/HsImport.hs, src/Haskell/Ide/Engine/Plugin/Liquid.hs, src/Haskell/Ide/Engine/Plugin/Package.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, test/unit/ExtensibleStateSpec.hs
This splits out the hover work into the ghc-mod and (new) haddock plugin
=> Add pluginHoverProvider

src/Haskell/Ide/Engine/Transport/JsonStdio.hs
The `getNextReq` function was calling `exitProcess` causing whole application to exit too early.
=> Fix JsonStdio transport.

.circleci/config.yml, src/Haskell/Ide/Engine/Plugin/GhcMod.hs, src/Haskell/Ide/Engine/Plugin/HieExtras.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, test/unit/CodeActionsSpec.hs
Still need to add goto type definition support at some point. Also improves typo correction detection in ghc
=> Update haskell-lsp to 0.6.0.0 and improve code action detection

src/Haskell/Ide/Engine/Plugin/GhcMod.hs, test/functional/CodeActionsSpec.hs, test/testdata/CodeActionRename.hs
Inside rename code action workspaceEdit
Fixes #755
=> Don't provide both documentChanges and changes

src/Haskell/Ide/Engine/Plugin/GhcMod.hs, test/dispatcher/Main.hs, test/functional/SymbolsSpec.hs
=> Include full location for document symbols

README.md
=> Add more vim instructions to README

src/Haskell/Ide/Engine/Plugin/GhcMod.hs, test/functional/CodeActionsSpec.hs, test/testdata/TypedHoles.hs, test/testdata/typedHoleDiag.txt, test/unit/CodeActionsSpec.hs, test/utils/TestUtils.hs
=> Typed hole code actions

appveyor.yml
Since we're running out of space
=> Disable appveyor artifacts for now

haskell-ide-engine.cabal, hie-plugin-api/Haskell/Ide/Engine/ArtifactMap.hs, hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs, hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs, src/Haskell/Ide/Engine/Plugin/GhcMod.hs, src/Haskell/Ide/Engine/Plugin/HaRe.hs, stack-8.2.1.yaml, stack-8.2.2.yaml, stack-8.4.2.yaml, stack-8.4.3.yaml, stack.yaml, test/functional/HaReSpec.hs, test/testdata/HaReLift.hs
Follows #759 
Allows other clients than vs code to access HaRe's refactoring!
=> HaRe code actions

docs/Design.md
=> Add outdation warning to Design.md

src/Haskell/Ide/Engine/Plugin/HsImport.hs, test/unit/CodeActionsSpec.hs
Needed to match on another type of error message
=> Add import suggestions for data constructors

src/Haskell/Ide/Engine/Plugin/HieExtras.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, test/functional/CompletionSpec.hs, test/testdata/completion/Completion.hs
=> Import autocomplete

src/Haskell/Ide/Engine/Plugin/GhcMod.hs, test/functional/DiagnosticsSpec.hs
Always sets the `DynFlag` '-fdefer-typed-holes'
Closes #790
=> Always defer typed holes

stack-8.2.1.yaml, stack-8.2.2.yaml, stack-8.4.2.yaml, stack-8.4.3.yaml, stack.yaml
=> Use extra-deps instead of extra-dep

src/Haskell/Ide/Engine/Transport/LspStdio.hs, test/functional/DeferredSpec.hs
=> Hover response can now be null

test/functional/FunctionalLiquidSpec.hs, test/unit/LiquidSpec.hs
Could be a different version of liquid
=> Fix liquid tests running on my machine locally

src/Haskell/Ide/Engine/Plugin/GhcMod.hs, test/functional/FunctionalCodeActionsSpec.hs, test/testdata/TopLevelSignature.hs, test/unit/CodeActionsSpec.hs
=> Added code action to insert missing top level signature

src/Haskell/Ide/Engine/Transport/LspStdio.hs, test/functional/CompletionSpec.hs
Might want to turn on whitespace ignore in the diff
=> Fix completions not returning anything when there's no prefix

src/Haskell/Ide/Engine/Plugin/HieExtras.hs, test/functional/CompletionSpec.hs
=> Fix argumentless constructors having snippets

hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs, src/Haskell/Ide/Engine/Dispatcher.hs, src/Haskell/Ide/Engine/Plugin/HieExtras.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs
=> Do not defer completion requests.

src/Haskell/Ide/Engine/Plugin/HieExtras.hs, test/functional/CompletionSpec.hs
=> Completion for pragmas

.circleci/config.yml
Looks like ghc-mod is failing?
=> Bump circleCI cache

.circleci/config.yml, Makefile, stack-8.4.3.yaml, stack-8.4.4.yaml, test/utils/TestUtils.hs
ghc-exactprint needed an update, to 0.5.8.2
Fixes #906
=> GHC 8.4.4 support

src/Haskell/Ide/Engine/Plugin/HaRe.hs
Extracts the common make action pattern into a `mkAction` function.
=> Simplify HaRe CodeAction construction

shell.nix
=> adding nix shell for building and using HIE

hie-plugin-api/Haskell/Ide/Engine/Config.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs, test/functional/FunctionalLiquidSpec.hs, test/unit/JsonSpec.hs
These requests are not debounced either. Also add config option to control debouncing duration
=> Run diagnostics on save

Makefile
Address https://github.com/haskell/haskell-ide-engine/issues/971 and https://github.com/haskell/haskell-ide-engine/issues/978 right here so end-users can have a more stable experience.
=> Address `#971` for good.

Makefile
=> Refactoring the makefile to use macros

src/Haskell/Ide/Engine/Plugin/HieExtras.hs, test/functional/CompletionSpec.hs
Otherwise we end up with two of them.
Closes  #994
=> Strip leading '-' from OPTIONS_GHC completions

hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs, hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs, hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs, src/Haskell/Ide/Engine/LSP/Reactor.hs, src/Haskell/Ide/Engine/Plugin/GhcMod.hs, src/Haskell/Ide/Engine/Transport/LspStdio.hs
Closes #1017
Closes https://github.com/alanz/vscode-hie-server/issues/129
=> Remove unprotected 'head` in GhcMod codeactions

Shakefile.hs
=> Add 8.4.2 and 8.2.1 HIE versions to Shakefile

Shakefile.hs
#1032 but for Shakefile. Part of #1033
=> Sync & update submodules recursively in Shakefile

app/MainHie.hs, cabal.project, haskell-ide-engine.cabal, src/Haskell/Ide/Engine/Options.hs, stack-8.6.1.yaml, stack-8.6.2.yaml, stack-8.6.3.yaml, stack.yaml
With increasing build times it would be wise to start trimming some dependencies.
Speak now or forever hold your peace!
=> Remove EKG

install.hs
=> Unhardcode script name in help message of install.hs

README.md
=> Fix documentation for build-doc instructions

src/Haskell/Ide/Engine/Plugin/Floskell.hs
- Respect `floskell` configuration file that can be found according to `floskell`'s rules.
=> Load Floskell configuration

.gitmodules, src/Haskell/Ide/Engine/Plugin/Floskell.hs, test/functional/FormatSpec.hs
point back to upstream version
=> Bump floskell

.circleci/config.yml, .gitmodules, Makefile, build-all.ps1, cabal.project, install.hs, stack-8.6.4.yaml, test/utils/TestUtils.hs
Some tests fail, need to investigate
=> Add GHC 8.6.4 support

.gitmodules, appveyor.yml, cabal.project, stack-8.6.4.yaml, stack.yaml
And use original author upstream for `floskell` submodule.
=> Remove monad dijkstra submodule

stack-8.6.3.yaml, stack-8.6.4.yaml, stack.yaml
And make sure that hlint latest version is used.
=> Use LTS for GHC 8.6.4

install.hs
Closes #1059 
No one claimed that they are actively using it, thus, remove to reduce dependencies.
=> Remove dist target

src/Haskell/Ide/Engine/Plugin/Pragmas.hs
=> Add EmptyDataDecls to available pragmas

src/Haskell/Ide/Engine/Plugin/Haddock.hs
As per @Hogeyama  comment at
https://github.com/haskell/haskell-ide-engine/pull/1189#issuecomment-485690789
=> Undo unnecessary changes from #1189

src/Haskell/Ide/Engine/Channel.hs
I changed “cam” to “can” on line 16.
=> Fixed a typo.

src/Haskell/Ide/Engine/Plugin/Package.hs
Not as in-depth as I wished, though.
=> Add Documentation for Package Plugin

.circleci/config.yml, .gitmodules, cabal.project, haskell-ide-engine.cabal, stack-8.2.1.yaml, stack-8.2.2.yaml, stack-8.4.2.yaml, stack-8.4.3.yaml, stack-8.4.4.yaml, stack-8.6.1.yaml, stack-8.6.2.yaml, stack-8.6.3.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack.yaml
Thanks to @ennocramer for the upload https://github.com/ennocramer/floskell/issues/6#issuecomment-489230007
=> Use floskell from hackage

haskell-ide-engine.cabal, hie-plugin-api/hie-plugin-api.cabal, stack-8.2.1.yaml, stack-8.2.2.yaml, stack-8.4.2.yaml, stack-8.4.3.yaml, stack-8.4.4.yaml, stack-8.6.1.yaml, stack-8.6.2.yaml, stack-8.6.3.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack.yaml, test/functional/HoverSpec.hs
Which makes the liquidhaskell hover messages render better.
=> Bump haskell-lsp to 0.13.0.0

shake.yaml
=> Bump shake resolver

stack-8.2.2.yaml, stack-8.4.2.yaml, stack-8.4.3.yaml, stack-8.4.4.yaml, stack-8.6.1.yaml, stack-8.6.2.yaml, stack-8.6.3.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack.yaml
Ready for the next monthly release
=> Bump resolvers and hoogle

hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
Fixes https://github.com/haskell/haskell-ide-engine/issues/1286
=> Fix file mapping state when we have a parsed module but not a typechecked module

.gitmodules, cabal.project, stack-8.2.2.yaml, stack-8.4.2.yaml, stack-8.4.3.yaml, stack-8.4.4.yaml, stack-8.6.1.yaml, stack-8.6.2.yaml, stack-8.6.3.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack.yaml
From hackage, rather than as a submodule.
=> Brittany 0.12

test/unit/LiquidSpec.hs
Related with #713 
This is the easier one :wink:
=> Fix liquid unit test normalizing paths

src/Haskell/Ide/Engine/Support/HieExtras.hs
This fixes https://github.com/neoclide/coc.nvim/issues/1040
=> Fix completionItem/resolve sending snippets as plain text

stack-8.6.5.yaml, stack.yaml
lts-13.30 for GHC 8.6.5, and nightly-2019-07-31
=> Monthly resolver bump

app/HieWrapper.hs
Helps debug cases such as https://github.com/alanz/vscode-hie-server/issues/145
=> Log OS in hie-wrapper

cabal.project, test/utils/TestUtils.hs
Currently the tests force using `stack`, but HIE should be an equal opportunity build system employer :)
Remember to read commit messages for details.
---
TODO:
=> Towards testing with cabal

src/Haskell/Ide/Engine/LSP/Completions.hs
Previous logic for establishing whether the completion happens in an infix context was messy.
This aims to improve the readability.
=> Refactor backtick aware completion

GenChangelogs.hs
Need to tidy up but my flight is boarding now!
Closes #1321
=> Hack awful script for generating changelog

.gitmodules
Now that https://github.com/DanielG/cabal-helper/commit/5b6cefdbe03ebc4ec6451751fbaba72cab663766 is merged, thanks @DanielG!
=> Switch back to @DanielG cabal-helper

README.md
Section doesn't exist (anymore). Therefore better to remove.
=> Readme: Remove non-existing troubleshooting entry

stack-8.6.5.yaml
Small one, only stack-8.6.5 moving to lts-14.20
=> Bump resolvers.

hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
Since it is now possible to release hie on Hackage, we want Haddock Documentation to render properly. These changes are mainly improvements to Haddock. No code functionality has been touched.
=> Fix haddock documentation for Cradle.hs

.azure/linux-stack.yml, .azure/macos-stack.yml, .azure/windows-installhs-stack.yml, .azure/windows-stack.yml, azure-pipelines.yml, test/functional/DiagnosticsSpec.hs, test/functional/FunctionalLiquidSpec.hs, test/unit/CabalHelperSpec.hs
* Tests
* Fix a intermittent failing test in `FunctionalLiquidSpec` due to interleaved diagnostics responses from the server
* Add to `CabalHelperSpec` a test to check explicitly that `stack`and `cabal` are in $PATH
* Azure
* Change `stack-root`to `D:` cause it seems the `C:` drive of azure agents is already almost full
=> Azure builds improvements

.azure/linux-stack.yml, .azure/macos-stack.yml, .azure/windows-stack.yml, README.md
=> Remove hlint.yaml from azure releases and readme

README.md
=> Update required stack version

README.md
See https://github.com/haskell/haskell-language-server/pull/31
=> Readme: haskell-ide -> haskell-language-server

README.md
Fix trailing comma for consistencies sake and because trailing commas aren't valid json
=> Remove Comma

README.md
=> Replace one more haskell-ide ocurrence

.azure/windows-cabal.yml, .azure/windows-stack.yml
* :wrapper-test and :plugin-dispatcher-test for windows
=> Enable some more tests in windows

cabal.project, cabal.project-8.8.2, haskell-ide-engine.cabal, stack-8.4.2.yaml, stack-8.4.3.yaml, stack-8.4.4.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.1.yaml, stack-8.8.2.yaml, stack.yaml
Bump resolvers and hlint to 2.2.11
=> Bump resolvers and hlint to 2.2.11

cabal.project, cabal.project-8.8.2, haskell-ide-engine.cabal, stack-8.4.2.yaml, stack-8.4.3.yaml, stack-8.4.4.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.1.yaml, stack-8.8.2.yaml, stack.yaml
It will need to be rebased onto #1678 
Fixes #1649
=> Use  haskell-src-exts 1.22

src/Haskell/Ide/Engine/Plugin/HsImport.hs
=> HsImport: Return codeactions importing from Internal modules last

Changelog.md, haskell-ide-engine.cabal, hie-plugin-api/hie-plugin-api.cabal
Prepare release for version 1.3
=> Prepare version 1.3

cabal.project, haskell-ide-engine.cabal, hie-plugin-api/Haskell/Ide/Engine/Cradle.hs, stack-8.4.2.yaml, stack-8.4.3.yaml, stack-8.4.4.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack-8.8.3.yaml, stack.yaml
Mainly for using the CI to detect problems
=> Update to hie-bios 0.5.0

cabal.project
=> Bump cabal index-state to include hie-bios-0.5.0
