haskell/haskell-ide-engine

- README.md
- docs/Challenges.md
Hello @alanz and @hvr
Thank you very much for starting this project.
I hope that this PR will clarify what this project is all about, and will help driving the discussion forward.
[You can see my modified readme here](https://github.com/rvion/haskell-ide-engine/tree/tweak-readme#haskell-ide-engine)
------------
This PR is not necessarily meant to be merged, I just wanted to share my view.
> [RFC] New readme for the project

- README.md
Citation for spelling: [supersede – Wiktionary](https://en.wiktionary.org/wiki/supersede#English)
> Fix spelling of ‘supersede’ in README

- haskell-ide-example-plugin2/Haskell/Ide/ExamplePlugin2.hs
- haskell-ide-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- haskell-ide-plugin-ghcmod/Haskell/Ide/GhcModPlugin.hs
- haskell-ide-plugin-hare/Haskell/Ide/HaRePlugin.hs
- src/Haskell/Ide/Engine/BasePlugin.hs
This allows us to expose a command for a .hs file, or a .cabal file, etc
> Introduce cmdFileExtensions for the CommandDescriptor

- elisp/tests/haskell-ide-engine-tests.el
- haskell-ide-engine.cabal
- haskell-ide-example-plugin2/Haskell/Ide/ExamplePlugin2.hs
- haskell-ide-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- haskell-ide-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- haskell-ide-plugin-ghcmod/Haskell/Ide/GhcModPlugin.hs
- haskell-ide-plugin-hare/Haskell/Ide/HaRePlugin.hs
- src/Haskell/Ide/Engine/BasePlugin.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
- test/DispatcherSpec.hs
- test/GhcModPluginSpec.hs
- test/HaRePluginSpec.hs
Move request validation into the dispatcher.
Now the `cmdFunc` is only ever called if the parameters in its request comply with at least one of its `AcceptedContext` values and all additional reuired parameters are present.
> Dispatcher validation

- haskell-ide-engine.cabal
- haskell-ide-example-plugin2/Haskell/Ide/ExamplePlugin2.hs
- haskell-ide-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- haskell-ide-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- haskell-ide-plugin-api/haskell-ide-plugin-api.cabal
- haskell-ide-plugin-ghcmod/Haskell/Ide/GhcModPlugin.hs
- haskell-ide-plugin-ghcmod/haskell-ide-plugin-ghcmod.cabal
- haskell-ide-plugin-hare/Haskell/Ide/HaRePlugin.hs
- haskell-ide-plugin-hare/haskell-ide-plugin-hare.cabal
- src/Haskell/Ide/Engine/BasePlugin.hs
- src/Haskell/Ide/Engine/Console.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
- test/DispatcherSpec.hs
- test/GhcModPluginSpec.hs
- test/HaRePluginSpec.hs
- test/JsonStdioSpec.hs
So apart from my terrible names (that's why it's marked as WIP), there are a couple of things here.
- The `Rec` datatype is the same as the one from Vinyl, I am not sure if it's worth pulling that in as a dependency for only one type.
- The duplication is not nice, the problem is that we need to stuff that in the map and maps want a monomorphic type, so you would need to put it in a RankNType to hide the tag, but that still doesn't work because now you can no longer derive Generic and Show. Show is easily fixable using StandaloneDeriving, Generic is not because you can't derive Generic for RankNTypes. We can just not derive Generic, but we need that for the json stuff, so we would need to manually write a ToJSON and FromJSON instance for ParamMap which doesn't seem to be easily possible …
> Use a GADT parametrized by param type, fixes #54

- haskell-ide-example-plugin2/Haskell/Ide/ExamplePlugin2.hs
- haskell-ide-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- haskell-ide-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- haskell-ide-plugin-ghcmod/Haskell/Ide/GhcModPlugin.hs
- haskell-ide-plugin-hare/Haskell/Ide/HaRePlugin.hs
- src/Haskell/Ide/Engine/BasePlugin.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
- test/DispatcherSpec.hs
- test/GhcModPluginSpec.hs
- test/HaRePluginSpec.hs
Hello, not sure if that's useful, but at least it forced me to have a look a bit everywhere in the code (-:. This replaces simple string errors by more structured ones, with a code, a human readable string and some JSON parameters. Also, I've removed calls to error to return IdeResponseFail.
> Error structure with code

- app/MainHie.hs
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/BasePlugin.hs
Do not suggest or encourage using state in plugins, not in the form of current working directory.
Reference #45.
> Remove state cwd

- elisp/tests/haskell-ide-engine-tests.el
Significantly speed up Emacs testing.
> Short cut sleeping when result is available

- elisp/tests/haskell-ide-engine-tests.el
- haskell-ide-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- src/Haskell/Ide/Engine/BasePlugin.hs
An Editor's side it is rare to work with a single command so it makes sense to batch queries about all available commands and command details.
This commits puts all the information about a plugin into 'plugins' call and remove the (now redundant) 'commands' and 'commandDetails' calls.
> Enrich plugins call

- haskell-ide-engine.cabal
- haskell-ide-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
So we now exit if we get invalid input which means either a parse failure or some random stuff between a parse and a separator. in particular that means that each message must be followed by a separator directly which seems reasonable to me.
> Expect json input separated by STX, fix #43

- app/MainHie.hs
- haskell-ide-engine.cabal
- haskell-ide-example-plugin2/Haskell/Ide/ExamplePlugin2.hs
- haskell-ide-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- haskell-ide-plugin-ghcmod/Haskell/Ide/GhcModPlugin.hs
- haskell-ide-plugin-hare/Haskell/Ide/HaRePlugin.hs
- src/Haskell/Ide/Engine/BasePlugin.hs
- src/Haskell/Ide/Engine/Console.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/Transport/JsonHttp.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
- src/Haskell/Ide/Engine/Types.hs
- test/DispatcherSpec.hs
- test/GhcModPluginSpec.hs
- test/HaRePluginSpec.hs
Closes #67 
A plugin can decide on a per-command basis whether it should have the option to return an async result.
If so, it takes responsibility for managing whatever threads are required to create the async processing, but each message has a callback function for when the result is ready.
> Async dispatch

- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/BasePlugin.hs
- src/Haskell/Ide/Engine/Console.hs
- test/JsonSpec.hs
Elisp tests currently fail
Addresses #92
@cocreature or @gracjan please have a look at the elisp tests, the wire format has now changed.
This may also make the `ExtendedCommandDescriptor` unnecessary
> PluginDescriptor no longer serialisable.

- elisp/haskell-ide-engine.el
This supports commands like ghc-mod’s type command. Currently the information is only printed to the mini buffer.
Also there are some ugly workaround for what I consider flaws in our protocol. I’ll clean it up and try to fix the protocol, where I feel necessary and then we can merge this.
I’m not an elisp wizard so feel free to tell me what I should change.
> Support commands that only require a context

- elisp/hie.el
This is a bit controversial, in particular @gracjan doesn’t seem to like it a lot, but let me explain my reasoning and then see where the disucssion goes
- It makes the code cleaner and simpler by providing combinators for commonly used patterns. That’s the same reason why haskellers love their `Data.List`.
- It gives us a form of pattern matching which is amazing when working with alists which is what json is represented as in emacs.
Now to the counter arguments and why I don’t fully buy them:
- It introduces an external dependency.
elpa gives us dependency management and given that this seems to be how most people install packages these days it’s not a burden for users. People who use git submodules or whatever for managing their packages are expert enough to figure out how to get …
> Use dash.el

- hie-example-plugin2/Haskell/Ide/ExamplePlugin2.hs
- hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs
- hie-hare/Haskell/Ide/HaRePlugin.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- src/Haskell/Ide/Engine/BasePlugin.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
- test/DispatcherSpec.hs
- test/JsonSpec.hs
Text descriptions intended for the editor user, rather than for
messages between the editor and HIE.
closes #98 
I took the Overview text from the tools' Hackage descriptions, but no doubt they could be improved.
> add ShortName and Overview to PluginDescriptor

- elisp/hie.el
This puts the emacs mode in a state where it can already serve as a replacement for the ghc mod type info.
We should add a default keybinding for that command but I couldn’t figure out how to do that so I'll leave that for someone else and a separate pr :)
> Extract the first type of a type info response

- app/MainHie.hs
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Monad.hs
- src/Haskell/Ide/Engine/MonadFunctions.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
- stack.yaml
- test/DispatcherSpec.hs
- test/GhcModPluginSpec.hs
- test/HaRePluginSpec.hs
Updated logging to remove PCRE dependency
It now makes use of a blend of Control.Monad.Logger and Control.Logging,
in that it uses the monad logger log formatting functions, which
includes using TH for a location, and the Control.Logging IORef process,
so logging is available in any thread that has access to IO.
At the moment it has the same flushing behaviour as before.
Closes #112 
cc @bergey
> New logger

- elisp/hie.el
- elisp/tests/hie-tests.el
> (elisp) Add log of hie process input / output

- docs/IdeIntegration.md
- hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/Haskell/Ide/Engine/SemanticTypes.hs
- test/DispatcherSpec.hs
- test/GhcModPluginSpec.hs
Implement the find command since it was a placeholder. The issue was that the find command in ghc-mod launches another copy of the executable. The source doesn't say why, and if dumping the symbol file in the same session should be avoided. It works without it: I basically just copied the code from findSymbol. The return type is a `ModuleList`, a specific type added to SemanticTypes.
A side effect is that CtxProject does require the project directory, since we need it for ghc-mod. So there's a `dir` parameter for CtxProject commands. Its type is still `PtFile`, not sure it's worth creating a different `PtDir` parameter type.
> Ghc mod find

- app/MainHie.hs
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/ExtensibleState.hs
- hie-plugin-api/Haskell/Ide/Engine/Monad.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/hie-plugin-api.cabal
- licenses/xmonad-contrib
- test/ApplyRefactPluginSpec.hs
- test/DispatcherSpec.hs
- test/ExtensibleStateSpec.hs
- test/GhcModPluginSpec.hs
- test/HaRePluginSpec.hs
Bring in a copy of [ExtensibleState](http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Util-ExtensibleState.html) from `xmonad-contrib` so that async commands can store a hook to get back to a running process, if needed.
Or any other purpose for state.
Note: Although the type for persistent state exists, the machinery to persist is not in place
Closes #83
> Plugin state

- hie-apply-refact/Haskell/Ide/ApplyRefactPlugin.hs
- hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs
- hie-hare/Haskell/Ide/HaRePlugin.hs
- hie-hare/hie-hare.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- hie-plugin-api/hie-plugin-api.cabal
As discussed via IRC, hare needs to be in the right folder. With this change, running a refactor command from Leksah generates a right answer (a diff). Progress!
> Hare context

- app/MainHie.hs
- haskell-ide-engine.cabal
- hie-eg-plugin-async/Haskell/Ide/ExamplePluginAsync.hs
- hie-eg-plugin-async/Setup.hs
- hie-eg-plugin-async/hie-eg-plugin-async.cabal
- stack.yaml
- test/ExamplePluginAsyncSpec.hs
I am not sure if this should be in master, but I am getting tired of rebasing it.
Comments?
> Initial example async process plugin

- haskell-ide-engine.cabal
- hie-apply-refact/hie-apply-refact.cabal
- hie-base/Haskell/Ide/Engine/PluginTypes.hs
- hie-base/Haskell/Ide/Engine/SemanticTypes.hs
- hie-base/hie-base.cabal
- hie-hare/hie-hare.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/hie-plugin-api.cabal
- stack.yaml
- test/JsonSpec.hs
Puts the plugin and semantic types into their own package, so that a Haskell client can easily reuse them with minimal dependencies. Tested with Leksah, which allowed me to find a JSON deserialization bug (fixed + quickcheck tested).
Note: it seems PluginTypes does NOT compile with aeson 0.10. To investigate and possibly report as a Aeson bug?
> Base split

- elisp/hie.el
- haskell-ide-engine.cabal
- hie-hare/Haskell/Ide/HaRePlugin.hs
- test/HaRePluginSpec.hs
This is a bunch of different things but they built upon each other so splitting it up doesn’t really gain us anything.
In particular the generated functions now have docstrings, parameters and ask for the required paramaters when called interactively. Apart from that I also added support for the refactor type returned by hare-rename (and probably also a lot of the other hare commands, that was just what I tested). Currently I just overwrite the old buffer content. I know at least @alanz would like to have an ediff window so we should add an option like `hie-refactor-confirm` which when enabled causes an ediff window to pop up. There’s nothing particularly difficult about adding that, I simply haven’t gotten around to it yet. Imho that can be done in a separate commit as in the disucssions …
> Support more commands

- docs/Hacking.md
- src/Haskell/Ide/Engine/Transport/JsonHttp.hs
This changes the format of url requests from
```
curl -v -H "Content-Type: application/json" -X POST -d '{"cmd": "lint", "params":{"file":{"file":"/home/moritz/code/haskell/playground/src/Main.hs"}}}' http://localhost:8001/req/ghcmod
```
to
```
curl -v -H "Content-Type: application/json" -X POST -d '{"file":{"file":"/home/moritz/code/haskell/playground/src/Main.hs"}}' http://localhost:8001/req/ghcmod/lint
```
Imho this is a more intuitive. The double `file` parameter comes from the fact that the first is the parameter name and the second is the type so that’s nothing specific to the servant protocol.
> Move to a plugin/command url scheme

- hie-eg-plugin-async/Haskell/Ide/ExamplePluginAsync.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
"cmdA3" starts a long running process that sends three async messages back
> Starting to bring in async streaming command

- app/MainHie.hs
- src/Haskell/Ide/Engine/Options.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
- test/JsonStdioSpec.hs
Invoking `hie` with the `--one-shot` flag in JSON/stdio mode will process one command only and then exit
> One shot invocation

- hie-apply-refact/Haskell/Ide/ApplyRefactPlugin.hs
- hie-apply-refact/hie-apply-refact.cabal
- hie-base/Haskell/Ide/Engine/PluginTypes.hs
- hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs
- hie-hare/Haskell/Ide/HaRePlugin.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- src/Haskell/Ide/Engine/BasePlugin.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
- stack.yaml
- test/DispatcherSpec.hs
- test/GhcModPluginSpec.hs
- test/HaRePluginSpec.hs
There are two minor changes here:
- I adapted the ApplyRefactPlugin to the new hlint api.
- I slightly changed the encoding of `IdeError`. Previously we had a Maybe Value which causes issues with the new aeson (I haven’t looked into why we didn’t run into it with the old version) since both `Nothing` and `Just Null` are encoded to `Null` so we no longer have an isomorphism. Since we already have a `Null` value in `Value` and I don’t think we need the distinction here, this is now just a `Value`.
> Bump deps and adapt to new apis

- app/MainHie.hs
- haskell-ide-engine.cabal
- hie-apply-refact/Haskell/Ide/ApplyRefactPlugin.hs
- hie-base/Haskell/Ide/Engine/PluginTypes.hs
- hie-base/Haskell/Ide/Engine/PluginTypes/Singletons.hs
- hie-base/hie-base.cabal
- hie-docs-generator/src/Examples.hs
- hie-docs-generator/src/Main.hs
- hie-docs-generator/src/Options.hs
- hie-eg-plugin-async/Haskell/Ide/ExamplePluginAsync.hs
- hie-example-plugin2/Haskell/Ide/ExamplePlugin2.hs
- hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs
- hie-hare/Haskell/Ide/HaRePlugin.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/BasePlugin.hs
- src/Haskell/Ide/Engine/Console.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/Transport/JsonHttp.hs
- src/Haskell/Ide/Engine/Transport/JsonHttp/Undecidable.hs
- src/Haskell/Ide/Engine/Utils.hs
- test/ApplyRefactPluginSpec.hs
- test/DispatcherSpec.hs
- test/ExamplePluginAsyncSpec.hs
- test/ExtensibleStateSpec.hs
- test/GhcModPluginSpec.hs
- test/HaRePluginSpec.hs
- test/JsonSpec.hs
- test/UtilsSpec.hs
This is more of a POC than finished code, but hopefully it can help to start a discussion if we want to move in that direction.
Now let me explain my motivation for doing this:
In the current state servant knows pretty much nothing about our api. All it knows is that there are two routes, but it doesn’t know which plugins exists. That means that all the nice stuff servant brings us, like auto generated bindings is pretty much useless. In particular I played around with `servant-swagger` which works but the documentation it generates is useless for that exact reason (pinging @tobiasgwaaler since he wanted to work on that).
With this approach we get at least the plugins and the commands correctly documented although we can and probably should take this further so the parameters a command …
> [POC] Move plugin and command names to the typelevel

- hie-plugin-api/Haskell/Ide/Engine/ExtensibleState.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
This removes the persistence since we don’t need it.
Also it replaces the existential by Dynamic from Data.Dynamic.
In addition to that it replaces some undefined hacks
using ScopedTypeVariables.
> Refactor ExtensibleState

- hie-base/Haskell/Ide/Engine/PluginTypes.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
Use Aeson's built-in `with<type>` functions, plus a custom error message
at the end of the ParamValP parser's Alternative chain to improve error
messages when parsing JSON requests.
Before:
-------
```json
❯ echo '{"cmd":"base:commands","params":{"plugin": "hare"}}' | hie --one-shot | jq
{
"error": {
"msg": "FromJSONError \"failed to parse field params: empty\"",
"code": "ParseError",
"info": null
}
}
```
After:
------
```json
❯ echo '{"cmd":"base:commands","params":{"plugin": "hare"}}' | stack exec -- hie --one-shot | jq
{
"error": {
"msg": "FromJSONError \"failed to parse field params: expected text, file, or position object, encountered String\"",
"code": "ParseError",
"info": null
}
}
```
Closes #166
> Improve error messages in JSON parsing

- .travis.yml
- app/MainHie.hs
- haskell-ide-engine.cabal
- hie-ide-backend/Haskell/Ide/IdeBackend.hs
- hie-ide-backend/Setup.hs
- hie-ide-backend/hie-ide-backend.cabal
- hie-plugin-api/Haskell/Ide/Engine/MonadFunctions.hs
- stack.yaml
- test/IdeBackendPluginSpec.hs
There are a few things here:
* It doesn’t work properly if you call it on 2 files from different projects. Given that #161 will limit hie to only deal with one project at a time anyway, I would prefer to leave it like this and instead spend the time on #161.
* I only added the type command, there is nothing stopping as from adding more commands, I just wanted to start somewhere.
* A lot of this stuff is very similar to the things in `ExamplePluginAsync`. It would probably make sense to create an `hie-plugin-utils` package containing things which are not directly relevant to `hie` itself but can be reused by plugin authors.
Also I just realized that I forgot the tests, I’ll hopefully add those later this evening.
Pinging @mgsloan since he seemed to be interested in an `ide-backend` plugin.
> Add ide-backend plugin

- .travis.yml
- Makefile
- app/MainHie.hs
- haskell-ide-engine.cabal
- hie-apply-refact/Haskell/Ide/ApplyRefactPlugin.hs
- hie-apply-refact/hie-apply-refact.cabal
- hie-base/hie-base.cabal
- hie-docs-generator/hie-docs-generator.cabal
- hie-docs-generator/src/Examples.hs
- hie-docs-generator/src/Main.hs
- hie-eg-plugin-async/Haskell/Ide/ExamplePluginAsync.hs
- hie-eg-plugin-async/hie-eg-plugin-async.cabal
- hie-example-plugin2/Haskell/Ide/ExamplePlugin2.hs
- hie-example-plugin2/hie-example-plugin2.cabal
- hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs
- hie-ghc-mod/hie-ghc-mod.cabal
- hie-hare/Haskell/Ide/HaRePlugin.hs
- hie-hare/hie-hare.cabal
- hie-ide-backend/hie-ide-backend.cabal
- hie-plugin-api/Haskell/Ide/Engine/Monad.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/BasePlugin.hs
- src/Haskell/Ide/Engine/Transport/JsonHttp.hs
- stack_test.yaml
- test/ApplyRefactPluginSpec.hs
- test/DispatcherSpec.hs
- test/ExamplePluginAsyncSpec.hs
- test/ExtensibleStateSpec.hs
- test/HaRePluginSpec.hs
- test/IdeBackendPluginSpec.hs
Updated version of #165 so we can finally merge this.
> Fix warnings

- elisp/hie.el
This is very useful during debugging. At some point we might want to consider an option to completely turn off the log but it should either be completely enabled or disabled, the current state is weird.
> Emacs: log parse error even if there is no handler

- elisp/hie.el
- elisp/tests/hie-tests.el
This should recreate the `*hie-log*` and `*hie-process*` buffers if they are
used after they have been killed.
Fixes #121
> Recreate buffers if they have been killed

- app/MainHie.hs
- hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs
- hie-hare/Haskell/Ide/HaRePlugin.hs
- hie-hare/hie-hare.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- src/Haskell/Ide/Engine/Options.hs
- stack.yaml
- stack_test.yaml
- test/GhcModPluginSpec.hs
Now the cwd is only changed at startup, which means that every cabal
project requires it’s own hie instance.
This is not finished, but I thought that it might be easier to fix the remaining issues if we have something to look at.
In particular HaRe needs to expose functions that work in `GhcModT` instead of trying to setup it’s own ghc-mod session since that no longer works with ghc-mod 5.5.
Also the ide bindings need to be updated. They simply need to pass in the directory with the cabal file or any subdirectory of that (ghc-mod figures the root out in that case). They can either do that by starting `hie` with the correct cwd or by using `-r projectdir`. On the emacs front we can probably simply abuse haskell-mode’s session management to have one `hie` instance per project.
> ghc-mod 5.5

- app/MainHie.hs
- haskell-ide-engine.cabal
- hie-docs-generator/src/Examples.hs
- hie-plugin-api/Haskell/Ide/Engine/MonadFunctions.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/Options.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
- src/Haskell/Ide/Engine/Transport/JsonTcp.hs
- src/Haskell/Ide/Engine/Transport/Pipes.hs
- test/JsonStdioSpec.hs
Most of the stuff we use for stdio transport can be completely reused for the tcp transport, so I moved that to a separate module.
Regarding tests, I am aware that I didn’t add tests. I took a look at the stdio tests and they don’t actually test the transport but only test the encoding and decoding (which is shared between stdio and tcp). Ofc we could build hie, launch it as a separate process and then actually test the tcp transport and the stdio transport, but I wasn’t sure if it’s worth the trouble.
> TCP transport

- deploy-docs.sh
Remove force update of gh-pages documentation by cloning repo before running make command to generate documentation.
A solution to fix #163
> Clone gh-pages repo before deploy

- elisp/hie.el
- hie-apply-refact/Haskell/Ide/ApplyRefactPlugin.hs
- hie-base/Haskell/Ide/Engine/PluginTypes.hs
- hie-eg-plugin-async/Haskell/Ide/ExamplePluginAsync.hs
- hie-example-plugin2/Haskell/Ide/ExamplePlugin2.hs
- hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs
- hie-ghc-tree/Haskell/Ide/GhcTreePlugin.hs
- hie-hare/Haskell/Ide/HaRePlugin.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- src/Haskell/Ide/Engine/BasePlugin.hs
- test/DispatcherSpec.hs
- test/ExtensibleStateSpec.hs
- test/JsonSpec.hs
- test/UtilsSpec.hs
This now looks at a safety attribute within the `CommandDescriptor` type. It specifies one of `Safe`, `ChangeCurrent` or `ChangeAll`.
* `Safe` means that the command will not read anything from disk
* `ChangeCurrent` may read the current file from disk
* `ChangeAll` may read multiple files from disk
Within Emacs, when calling `hie-run-command`, it will now save buffers based on the level of safety.
* `Safe` nothing happens
* `ChangeCurrent` will ask to save the current buffer
* `ChangeAll` will ask to save all buffers
Fixes #189
> Save modified buffer when calling hie commands

- hie-brittany/Haskell/Ide/BrittanyPlugin.hs
- stack.yaml
compiles, but otherwise untested (my editor doesn't support lsp sufficiently well yet, i fear).
This is not necessarily supposed to be a permanent solution; it would generally be preferable to have the extensions used be configurable by the user or to have them determined from the module/project environment (cabal file etc.).
> brittany plugin: Enable syntactic extensions by default

- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- stack.yaml
If a file is badly broken it can end up with a large number of diagnostics,
which can slow things down.
Limit the number sent to the client. This is currently hard coded to 50, but
should probably be settable via a command line option.
There is also a custom message from vscode to set this to a configuration value,
per project. It could perhaps honour that too.
> Limit number of diagnostics provided per file.

- hie-hare/Haskell/Ide/HaRePlugin.hs
- hie-hare/hie-hare.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- stack.yaml
- test/HaRePluginSpec.hs
1. Send the edits in reverse order, so that the line numbers are still valid, as
edits later in the file will not change line numbers earlier in the file.
2. When something is added, make sure the change is expressed with respect to
the file being changed, not the reference file for the diff.
>  Sort out overlapping edits

- README.md
- stack.yaml
Thanks to @ethercrow for removing `text-icu` as a dependency from `yi-rope`. This should now simply build with `stack install` on macOS.
I have never used nix and am not sure how it works, but I can only assume it's a simple as removing `icu` from this line https://github.com/haskell/haskell-ide-engine/blob/master/stack.yaml#L72. I'll leave that change for someone who can actually test it.
Perhaps someone could also test this on windows as I have no way of knowing if this `resolves` #300. 
Closes #303
> Fix builds on macOS

- README.md
Oh, and this should make https://github.com/haskell/haskell-ide-engine/pull/311 obsolete. Forgot that was there, and did it all in one fell swoop :/
> Clean up and organize the README

- README.md
This seemed to be just about the only thing that got the VS Code extension to stop complaining about a missing Hoogle database. Took me ages to figure it out, so hopefully this helps someone else!
> Add doc for gen. global hoogle db with stack

- app/MainHie.hs
It will pick up the options from .cabal
Closes #365 - Extra warnings were displayed
for people who used -Wall and -Wno-xxx flags.
An extra -Wall added by HIE just cancelled
the effect of -Wno switches.
This change breaks the behaviour for people who
omitted -Wall in their .cabal files and relied
on HIE to add the switch. They should just
add -Wall to ghc-options in .cabal.
> Don't force ghc-mod to use -Wall switch

- stack.yaml
Probably we need to clean our cache of cabal-helpers regularly to catch such problems (it's in another place from other build products)
See #329
> Use newer cabal-helper to avoid choking on CFLib

- app/MainHie.hs
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Options.hs
Launch with the `--ekg` option to `hie`, and point a browser at
http://localhost:8000
> Add EKG support

- src/Haskell/Ide/Engine/Transport/LspStdio.hs
Although it hides the real issue, this change allows HIE to continue to be used by getting rid of the incessant popups.
> Temporary workaround for #391

- README.md
Some markdown viewers won't load http images. (namely, vscode)
> Update README.md - use https for images

- hie-apply-refact/LICENSE
- hie-apply-refact/hie-apply-refact.cabal
- hie-base/LICENSE
- hie-base/hie-base.cabal
- hie-brittany/LICENSE
- hie-brittany/hie-brittany.cabal
- hie-build-plugin/LICENSE
- hie-build-plugin/hie-build-plugin.cabal
- hie-example-plugin2/LICENSE
- hie-example-plugin2/hie-example-plugin2.cabal
- hie-ghc-mod/LICENSE
- hie-ghc-mod/hie-ghc-mod.cabal
- hie-haddock/LICENSE
- hie-haddock/hie-haddock.cabal
- hie-hare/LICENSE
- hie-hare/hie-hare.cabal
- hie-hoogle/LICENSE
- hie-hoogle/hie-hoogle.cabal
- hie-plugin-api/LICENSE
- hie-plugin-api/hie-plugin-api.cabal
This is an unfortunate consequence of Nix packages
being restricted filesystem access to only root of
the package, so ../LICENSE doesn't exist.
> Convert all LICENSE files into copies

- Makefile
Following up on https://github.com/haskell/haskell-ide-engine/issues/439.
The Makefile makes it easy to build all the versions of HIE we have for different GHC versions. 
- It's intentionally sequenced with `&&`, so that `~/.local/bin/hie` doesn't get overwritten by another build (can one specify specific executable paths/names? with stack?)
- The reason for the redundant `~/.local/bin/hie-8.2` is merely that it is using the main `stack.yaml`, which I assume will be changed to a different GHC later on, and this will make sure we don't forget to add the `8.2` version of HIE.
- When we add new stack.yaml's or change GHC versions in the main config, we should update this accordingly.
This is meant to go with a wrapper script that automatically chooses the right version based on the GHC …
> Add Makefile for building all GHC variants

- README.md
Add installation instructions for windows users who are facing the `path too long` issue on windows. Addresses #435
> Add installation instructions for windows users

- Makefile
- app/MainHie.hs
- src/Haskell/Ide/Engine/BasePlugin.hs
- stack-8.0.2.yaml
- stack-8.2.1.yaml
- stack.yaml
to the startup version message, and version command.
So we now get
hie --version
Version 0.1.0.0, Git revision 9ad6d0c29ae1559202edba824453031fbc76ef8a (dirty) (1170 commits) x86_64 ghc-8.2.2
> Update to latest cabal-helper/ghc-mod, add ghc version

- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
This failed to build (with GHC 8.2.2):
```
error: \u used with no following hex digits; treating as '\' followed by identifier [-Werror,-Wunicode]
```
Adding a space resolved it on my machine.
> Fix build error

- Makefile
I didn't know about the `--copy-compiler-tool` flag in stack before reading [An Opinionated Guide to Haskell in 2018](https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/), but thought it would be an excellent way to setup hie.
Often I see people running into issues with the GHC hie was built with differing with the one they use in their project. I added a wrapper script to sorta alleviate this problem for myself (it's in the VSCode and Atom clients), but think it's a bit of a suboptimal solution.
So, this PR adds some preliminary support for building the different HIE versions tied specifically to the GHC compilers they were built on via `make build-copy-compiler-tool`. This way, a user that is using HIE on a mismatching GHC version will get an error if …
> Add Makefile build that uses --copy-compiler-tool, along with a make icu-macos-fix for icu4c problems

- Makefile
- circle.yml
We need to run `hoogle generate` with every version of hoogle we build and test with.
Also, only generate a subset db, otherwise it takes too long.
And strip out some builds that were unnecessary.
> Fix circleci build

- app/MainHie.hs
- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- src/Haskell/Ide/Engine/Types.hs
IF the module is not currently loaded, simply return an empty result
for hover request and document symbols request.
Affects #416, #460, #462
I am not sure that it closes any of them though.
> Do not return error message for hover and symbols req

- .gitignore
- Makefile
- cabal.project
- docs/Hacking.md
This does not gratuitously rebuild haddock-api and haddock-library for
every change made.
> Speed up dev cycle by using cabal new-build

- app/MainHie.hs
Is using `$HOME` as default root dir the desired behavior? It doesn't seem to me like a sensible default to use. Even the CLI docs say the default is current directory
```
-r,--project-root PROJECTROOT
Root directory of project, defaults to cwd
```
> Use current directory as default when project root is not specified

- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- test/ApplyRefactPluginSpec.hs
- test/Functional.hs
- test/testdata/FuncTestError.hs
- test/testdata/HlintParseFail.hs
And if hlint reports a parse error, do not report that either, by
setting the severity to DsInfo, which is not displayed.
Addresses #490
> Do not send hlint diagnostics when there is a ghc error reported

- README.md
> Add instructions for emacs to README

- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
Current nightly stack.yaml on macOS - `stack build` produces an error:
```
/Users/pavlo/Projects/haskell-ide-engine/src/Haskell/Ide/Engine/Plugin/GhcMod.hs:66:22: error:
error: \u used with no following hex digits; treating as '\' followed by identifier [-Werror,-Wunicode]
|
66 | checkCmd = CmdSync $ \uri ->
|                      ^
checkCmd = CmdSync $ \uri ->
^
```
The patch fixes it and lets `hie` to be built and installed.
> Fix warning: '\u used with no following hex digits' in GhcMod.hs

- stack.yaml
There is no longer need to use nightly builds of stack.
> Update resolver for ghc-8.2.2 to LTS

- README.md
+ The 'Hoogle docs on hover' header was changed to 'Docs on hover/completion' but not the link in the beggining of the README
+ This commit updates the link to point to the correct header
> Fix broken 'Docs on hover' link in README

- src/Haskell/Ide/Engine/Plugin/Brittany.hs
> Fix extra newline being added when formatting document

- .circleci/config.yml
- .gitmodules
- Makefile
- cabal.project
- stack-8.0.2.yaml
- stack-8.2.1.yaml
- stack.yaml
These can be set up once, and used for all builds, instead of needing
to be set per stack file, and in the cabal.project.
> Switch to using submodules for external repos

- .gitmodules
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginTypes.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/Brittany.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- src/Haskell/Ide/Engine/Types.hs
- stack-8.0.2.yaml
- stack-8.2.1.yaml
- stack.yaml
- test/ApplyRefactPluginSpec.hs
- test/DispatcherSpec.hs
- test/Functional.hs
- test/GhcModPluginSpec.hs
- test/HaRePluginSpec.hs
This is to match the upcoming change in the https://github.com/alanz/haskell-ide-engine/tree/ghc-8.4 branch, and will then create a hie-0.1.0.0 branch, which will be the last to support GHC 8.0.2.
> Update for haskell-lsp 0.2.1.0

- .gitmodules
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- stack-8.0.2.yaml
- stack-8.2.1.yaml
- stack-8.2.2.yaml
- stack.yaml
- test/ApplyRefactPluginSpec.hs
- test/Functional.hs
- test/GhcModPluginSpec.hs
Match changes in `haskell-lsp-types`
vscode was unhappy with non-optional relatedInformation field in a Diagnostic.
cc @Bubba
> Dignostic relatedInformation is optional in LSP

- stack-8.0.2.yaml
Seems like brittany is not in submodules anymore.
> stack-8.0.2.yaml: remove unused submodules

- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- test/ApplyRefactPluginSpec.hs
- test/testdata/HlintNoRefactorings.hs
This changes the code action request reactor to send a request to hlint.
It can use this information to determine if any of the diagnostics coming from the LSP client are actionable, and filter out the ones that aren't.
Fixes alanz/vscode-hie-server#61
> Don't provide code actions for diagnostics that hlint doesn't have refactorings for

- Makefile
Fixes #537 
Notes: 
`!=` is used to capture output of shell command. `$(shell cmd)` is GNU extension, so probably something will break on OSX. Paths are quoted otherwise make thinks that slashes are escaping on Windows.
> Use local bin path provided by stack

- src/Haskell/Ide/Engine/Transport/LspStdio.hs
This was a holdover from early experiments, and now breaks vscode.
Fixes https://github.com/alanz/vscode-hie-server/issues/65
> Do not register executeCommandProvider on startup

- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
`getTypecheckedModuleGhc'` returns diags with canonicalized URIs so dummy diags with un-canonicalized URI is always inserted to diags map.
Which leads to LSP client overwriting actual diags with dummy ones because both URI are treated the same.
Fixes #560
> Canonicalize uri for dummy diags

- hie-plugin-api/Haskell/Ide/Engine/Monad.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
So that instead of a silent hang, we get an actuall error message
back, and operation continues.
> Wrap exception handler around module loading.

- src/Haskell/Ide/Engine/Transport/LspStdio.hs
When there are multiple events in one didChange notification, they were getting applied from the last event to the first event which caused the text getting out of sync when undoing/redoing in VS Code. Fixes #566, possibly #531 but *not* #538
> Fix TextDocumentContentChangeEvents getting applied in the wrong order

- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
> Also catch IOError, for when cabal-helper fails.

- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- src/Haskell/Ide/Engine/Types.hs
- test/Functional.hs
- test/MainDispatcher.hs
As each request arrives in the reactor, it is given a tracking number.
This is passed into the dispatcher, and logged as the message is
processed.
This makes it easier to understand/tie back the message processing,
when tracking down bugs.
> Add a global message tracking number, for logging

- src/Haskell/Ide/Engine/Transport/LspStdio.hs
It is redundant, as we get the textDocument/didChange.
And may help with https://github.com/alanz/vscode-hie-server/issues/59
> Do not process the textDocument/didSave notification

- .gitignore
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Compat.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- stack-8.2.1.yaml
- stack-8.2.2.yaml
- test/Functional.hs
- test/TestUtils.hs
- test/testdata/ApplyRefact2.hs
Currently when starting multiple instances of HIE for the same client, it an errors due to registering the same commands multiple times in the initialise response that we send. This happens when creating a multi-root/project workspace in VS Code.
This was discussed [here](https://github.com/Microsoft/vscode-languageserver-node/issues/333) and the suggested solution was to use UUIDs to register commands. 
This PR changes the server to register random UUIDs, and maps back and forth between them in code action and execute command requests. You can still send an execute request for "hare:demote" as well as the new random UUID for it, and have the same command executed.
> Use UUIDs for commands

- haskell-ide-engine.cabal
I have encountered this error
> In the dependencies for haskell-ide-engine-0.2.0.0(+pedantic):
>     **win32** needed, but the stack configuration has no specified version (no package with that name
>           found, perhaps there is a typo in a package's build-depends or an omission from the
>           stack.yaml packages list?)
> needed since haskell-ide-engine is a build target.
> 
> Some different approaches to resolving this:
> 
>   * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some
>     working build configuration. This can be convenient when dealing with many complicated
>     constraint errors, but results may be unpredictable.
> Fix typo "win32" on haskell-ide-engine.cabal

- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
Realised that there's no need for UUIDs if we're basing it off of process IDs
> Use just plain process IDs instead of UUIDs to unique commands

- docs/Dispatch.md
- docs/Hacking.md
- docs/Packages.md
Should be enough to close #596
> Update some documentation

- app/HieWrapper.hs
- app/MainHie.hs
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/MonadFunctions.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Plugin/Base.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
Logs to the hie log, logs to the lsp log and shows a message to the user if the HIE ghc version doesn't match up with the project ghc version, should hopefully close #459 and #414, and many more support requests
> Check GHC version on launch

- stack-8.2.1.yaml
- stack-8.2.2.yaml
- test/Functional.hs
Should hopefully fix window builds on 8.2.1/8.2.2
> Update haskell-lsp-test to no longer require an extra-dep on process-1.6.3

- README.md
- make-build-all.bat
The command `make build-all` does not work on 'out of the box' Windows. There are work-arounds, for example the Cygwin installer has the option of including a `make` command. This pull request suggests taking the approach of providing a Windows batch file that replicates the function of `make build-all`.  
`README.md` is updated, accordingly.
> Add Windows batch equivalent of `make build-all`

- README.md
Note, this does not amend (correct) the advice in `README.md` about `"languageServerHaskell.useHieWrapper": true` (see https://github.com/alanz/vscode-hie-server/issues/97). I did not know if that advice was still good on unix-like operating systems.
> Re #669: Extend docs about make tool on Windows

- .circleci/config.yml
- Makefile
- src/Haskell/Ide/Engine/Plugin/Build.hs
- stack-8.2.1.yaml
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- test/Functional.hs
- test/GhcModPluginSpec.hs
Also introduce `stack-8.4.3.yaml` to track the LTS version.
`stack.yaml` will track nightly, and in time GHC 8.6.1
Superseds #673
> Update for LTS-12.0, bump resolvers where possible.

- haskell-ide-engine.cabal
Module `Haskell.Ide.Engine.Plugin.Build` uses `decodeThrow` which was added to the yaml package in version 0.8.31.
> Add lower bound on yaml version

- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- test/GhcModPluginSpec.hs
Should perhaps rename HarePoint type
> Use standard parameter form for caseSplit command.

- README.md
Which is required by ghc-mod/cabal-install.
Closes #658
> Add instructions to install cabal-install

- README.md
I've heard the cask install is no longer necessary. If so, you could merge this.
> Remove cask info

- .gitignore
- hie-plugin-api/Haskell/Ide/Engine/ArtifactMap.hs
- hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- test/functional/DefinitionSpec.hs
- test/testdata/definition/Bar.hs
- test/testdata/definition/Foo.hs
- test/testdata/definition/definitions.cabal
- test/utils/TestUtils.hs
This adds the ability to jump to a source file by making a goto definition request on an import statement. 
This also adds a map of imported module names to the GHC module cache to support it.
Closes #688
> Go to definition for project imports

- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- src/Haskell/Ide/Engine/LSP/CodeActions.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/Base.hs
- src/Haskell/Ide/Engine/Plugin/Brittany.hs
- src/Haskell/Ide/Engine/Plugin/Build.hs
- src/Haskell/Ide/Engine/Plugin/Example2.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HaRe.hs
- src/Haskell/Ide/Engine/Plugin/Hoogle.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Plugin/Package.hs
- test/unit/CodeActionsSpec.hs
- test/unit/ExtensibleStateSpec.hs
Code actions are now generated with a `CodeActionProvider` field on `PluginDescriptor`.
The first part of #701
> Refactor Code Actions

- .circleci/config.yml
- .gitignore
- app/MainHie.hs
- haskell-ide-engine.cabal
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/LSP/CodeActions.hs
- src/Haskell/Ide/Engine/LSP/Reactor.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Plugin/Package.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- test/functional/CodeActionsSpec.hs
- test/functional/CommandSpec.hs
- test/testdata/redundantImportTest/src/MultipleImports.hs
Does part of #701.
Both workspace edits and commands are now included in the `fallbackCodeAction` shim command.
Also gets rid of the command map which is now no longer needed, and automatically sends all plugin commands in the initialise request
> Improve backwards compatible code actions, simplify command mapping

- app/HieWrapper.hs
- app/MainHie.hs
- haskell-ide-engine.cabal
Otherwise it sometimes uses the wrong directory, and then defaults to
`hie` as the executable, which is normally `hie-8.4.3`.
Closes #714
> Use ghc-mod to find the project root for hie-wrapper

- Makefile
It seems that stack simply copies the exe over for `stack install`, does not build it if it is out of date.
> Make sure that we build the exes before installing them

- app/MainHie.hs
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- src/Haskell/Ide/Engine/LSP/CodeActions.hs
- src/Haskell/Ide/Engine/LSP/Config.hs
- src/Haskell/Ide/Engine/LSP/Reactor.hs
- src/Haskell/Ide/Engine/Options.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/Base.hs
- src/Haskell/Ide/Engine/Plugin/Brittany.hs
- src/Haskell/Ide/Engine/Plugin/Build.hs
- src/Haskell/Ide/Engine/Plugin/Example2.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HaRe.hs
- src/Haskell/Ide/Engine/Plugin/Hoogle.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Plugin/Liquid.hs
- src/Haskell/Ide/Engine/Plugin/Package.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- src/Haskell/Ide/Engine/Types.hs
- test/functional/DiagnosticsSpec.hs
- test/unit/ExtensibleStateSpec.hs
- test/utils/TestUtils.hs
Adds the ability for a given plugin to generate diagnostics.
These can be triggered from any set of `DidOpen`, `DidChange` or `DidSave` notifications.
Still need to add a config option to enable the example plugin, else normal users will get spammed with junk.
> diagnostic providers

- .circleci/config.yml
Useful for quickly grabbing a binary for testing lsp-test with, **not** for releasing/distributing
> Store binary artifacts on CircleCi

- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
Previously only the first import would have shown up when
entering the qualified completion, e.g. if you had
```haskell
import qualified A as Foo
import qualified B as Foo
Foo.bar
```
Only A's suggestions would show up.
> Fix completion when two imports have the same qualifier

- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- test/functional/FunctionalCodeActionsSpec.hs
- test/functional/FunctionalSpec.hs
- test/functional/Main.hs
- test/functional/Spec.hs
- test/testdata/TypedHoles2.hs
- test/testdata/typedHoleDiag2.txt
- test/testdata/typedHoleDiag3.txt
- test/unit/CodeActionsSpec.hs
This implements what is described in #767
I took the liberty of renaming one test file, so I could run the tests
from inside ghci. Without the rename, it would complain about duplicate
module names
closes #767
> Improved the suggestions for typed holes actions

- README.md
In one of my stack projects I was still getting the `Got error while processing diagnostics: readCreateProcess` error mentioned in https://github.com/haskell/haskell-ide-engine/issues/658, although I had run `stack install cabal-install` like mentioned in the README (added by https://github.com/haskell/haskell-ide-engine/pull/702).
I saw in https://github.com/haskell/haskell-ide-engine/issues/658 that @rszibele had fixed the issue by installing `cabal` *and* running `cabal update`. So I ran `cabal update` and that seemed to fix it for me as well.
Note that for other stack projects I didn't get that error. I'm not sure what was different about this one.
> Add instructions to run cabal update

- docs/Architecture.md
- hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/Monad.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/LSP/CodeActions.hs
- src/Haskell/Ide/Engine/LSP/Reactor.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/Haddock.hs
- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Plugin/Liquid.hs
- src/Haskell/Ide/Engine/Plugin/Package.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- src/Haskell/Ide/Engine/Types.hs
- test/dispatcher/Main.hs
- test/functional/DeferredSpec.hs
- test/unit/HaRePluginSpec.hs
This removes the whole `IdeResponse`/`pluginGetFileResponse` headache. Use `IdeResult` now instead.
It also removes the versions of `withCachedModule` that didn't take a default. Now they must provide a default fallback if there is no module (which most of them did anyway), removing the `NoModuleAvailable` error code.
The dispatcher now also handles all the logic for deferred responses now, whereas previously half of it was in`ModuleCache.hs` as well.
> Remove IdeResponse, integrate it into IdeM as FreeT IdeDefer

- docs/Architecture.md
- hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/Monad.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/LSP/CodeActions.hs
- src/Haskell/Ide/Engine/LSP/Reactor.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HaRe.hs
- src/Haskell/Ide/Engine/Plugin/Haddock.hs
- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Plugin/Liquid.hs
- src/Haskell/Ide/Engine/Plugin/Package.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- src/Haskell/Ide/Engine/Types.hs
- test/dispatcher/Main.hs
- test/functional/DeferredSpec.hs
- test/unit/HaRePluginSpec.hs
> Revert #777 and #782, performance was awful

- stack-8.2.1.yaml
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack.yaml
Recently a new revision of cabal-helper-0.8.1.0 was uploaded to Hackage, but due to [this issue](https://github.com/haskell/haskell-ide-engine/issues/784#issuecomment-416075778) it causes hie to fail when building via stack. This specifies the first revision to circumvent this until it is fixed
Fixes #784, superseeds #788
> Specify cabal-helper revision

- app/MainHie.hs
- docs/Architecture.md
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/Monad.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Dispatcher.hs
- src/Haskell/Ide/Engine/LSP/CodeActions.hs
- src/Haskell/Ide/Engine/LSP/Reactor.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HaRe.hs
- src/Haskell/Ide/Engine/Plugin/Haddock.hs
- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Plugin/Liquid.hs
- src/Haskell/Ide/Engine/Plugin/Package.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- src/Haskell/Ide/Engine/Types.hs
- test/dispatcher/Main.hs
- test/functional/DeferredSpec.hs
- test/functional/HaReSpec.hs
- test/unit/HaRePluginSpec.hs
- `codeActionProviders` can no longer defer
- Add `ifCachedModule`/`ifCachedModuleAndData` counterparts to `withCachedModule[AndData]`
- Remove `getCachedModule`/`isCached` to simplify/normalise how cached modules are accessed
- Remove `isStale` in `CachedModule` since it wasn't used
> Remove IdeResponse, split out IdeM into IdeM and IdeDeferM

- .circleci/config.yml
- stack-8.4.3.yaml
- stack.yaml
I had to blow away the precompiled caches in `~/.stack`, else
`haddock-library` fails to compile, with a dependency version mismatch.
> Spring day (in the south). Update resolvers.

- .circleci/config.yml
The cache keys are cascading fallbacks, so .stack/.cache/.stack-work should all be cached at once
> Fix circle ci work dir caching

- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- test/functional/FunctionalLiquidSpec.hs
- test/unit/CodeActionsSpec.hs
This improves the code action for correcting typos, it now picks
suggestions consisting of qualified names and filters out things that
are not actuallly suggestions.
I took again the liberty of renaming a test module so that I could run the tests from ghci.
> Improved suggestions for mispelled variables

- haskell-ide-engine.cabal
- stack-8.2.1.yaml
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack.yaml
- test/functional/CommandSpec.hs
- test/functional/CompletionSpec.hs
- test/functional/DeferredSpec.hs
- test/functional/DefinitionSpec.hs
- test/functional/DiagnosticsSpec.hs
- test/functional/FormatSpec.hs
- test/functional/FunctionalCodeActionsSpec.hs
- test/functional/HaReSpec.hs
- test/functional/HighlightSpec.hs
- test/functional/HoverSpec.hs
- test/functional/LiquidSpec.hs
- test/functional/ReferencesSpec.hs
- test/functional/RenameSpec.hs
- test/functional/SymbolsSpec.hs
Removes the spam of logs during testing
> Update to haskell-lsp-0.7.0.0, lsp-test-0.3.0.0

- .gitignore
- app/MainHie.hs
- test/functional/DiagnosticsSpec.hs
- test/testdata/wErrorTest/src/WError.hs
- test/testdata/wErrorTest/test.cabal
- test/utils/TestUtils.hs
When having -Werror enabled, the experience with HIE degrades
significantly as everything is treated as a type error. This makes sure
that warnings are always treated as warnings.
closes #449, #680 and #662
> Ignoring the -Werror setting

- README.md
Unexpected trailing characters
> Error while parsing the LSP settings

- .gitmodules
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/ModuleCacheTypes.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/LSP/CodeActions.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HaRe.hs
- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Plugin/Package.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- stack-8.2.1.yaml
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack.yaml
- test/dispatcher/Main.hs
- test/functional/CommandSpec.hs
- test/functional/CompletionSpec.hs
- test/functional/DeferredSpec.hs
- test/functional/DefinitionSpec.hs
- test/functional/DiagnosticsSpec.hs
- test/functional/FunctionalCodeActionsSpec.hs
- test/functional/FunctionalLiquidSpec.hs
- test/functional/HaReSpec.hs
- test/functional/HoverSpec.hs
- test/functional/ReferencesSpec.hs
- test/functional/RenameSpec.hs
Closes #822 
The haskell-lsp-0.8 update mainly involves importing/removing Lens imports.
> Update to haskell-lsp-0.8 and fix snippet not respecting client capabilities

- Makefile
It now executes "make help" by default and shows what is possible, instead of building all versions immediately. This is a sample output:
refs #856
[ci skip]
> Makefile shows help by default instead of building all

- app/MainHie.hs
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- src/Haskell/Ide/Engine/LSP/CodeActions.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/Base.hs
- src/Haskell/Ide/Engine/Plugin/Brittany.hs
- src/Haskell/Ide/Engine/Plugin/Build.hs
- src/Haskell/Ide/Engine/Plugin/Example2.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HaRe.hs
- src/Haskell/Ide/Engine/Plugin/HfaAlign.hs
- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- src/Haskell/Ide/Engine/Plugin/Hoogle.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Plugin/Liquid.hs
- src/Haskell/Ide/Engine/Plugin/Package.hs
- src/Haskell/Ide/Engine/Transport/JsonStdio.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- test/dispatcher/Main.hs
- test/unit/ApplyRefactPluginSpec.hs
- test/unit/BrittanySpec.hs
- test/unit/ExtensibleStateSpec.hs
- test/unit/GhcModPluginSpec.hs
- test/unit/HaRePluginSpec.hs
- test/utils/TestUtils.hs
http://www.haskellforall.com/2018/10/detailed-walkthrough-for-beginner.html
As demonstrated at haskellX 2018.
A lot of this is plumbing through access to the VFS to be able to get the source text for a LSP `Range`, which is useful for all plugins anyway.
The actual work is in `HfaPlugin.hs`, where only the first 75 lines are for the plugin the rest is the code from @Gabriel439 's blog post.
> Add example code for haskellforall.com blog post

- app/MainHie.hs
- haskell-ide-engine.cabal
- stack.yaml
`haskell-ide-engine` depends on `warp` and `wai`, but `ekg` pulls in `snap` and the associated `io-streams` libraries. 
This PR switches from `ekg` to `ekg-wai`, which is a drop-in replacement for `ekg` that only depends on the `wai` ecosystem and drops total dependencies from 237 to 235 (it adds `wai-app-static` and `wai-extra`).
Dunno if this is meaningfully useful to the project, but I figured it's an easy win to avoid compiling an additional web framework and streaming library 😄
> Switches to ekg-wai

- make-build-all.bat
#674 introduced `stack-8.4.3.yaml` to `Makefile`. This makes the corresponding change to `make-build-all.bat`.
> Copy #674 for make-build-all.bat

- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- test/functional/CompletionSpec.hs
- test/testdata/completion/Completion.hs
First try at resolving #867.
This adds completion for language extensions.
This changes the behaviour of completion generation to only generate completions for language extensions on lines beginning with "{-# LANGUAGE", perhaps we should modify this so it works even if the line just contains "LANGUAGE": `{-#LANGUAGE` and `{-#   LANGUAGE` would then also work.
This adds a `cachedExtensions` field to the `CachedCompletions` record, which is filled via the Ghc api. Going through GhcMod would be much more complicated, since [in ghcmod](https://github.com/DanielG/ghc-mod/blob/master/GhcMod/Exe/Lang.hs#L10) a nice list of language extensions is squashed into a string, which we'd have to parse back. Instead I just get the list via [this](https://hackage.haskell.org/package/ghc-8.6.1/docs/DynFlags …
> Add completion for Language Extensions

- stack-8.4.2.yaml
Don't know why this is needed all of a sudden, should hopefully fix appveyor builds
> Add windns extra-dep for 8.4.2

- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- test/functional/FunctionalCodeActionsSpec.hs
- test/testdata/UnusedTerm.hs
- test/unit/CodeActionsSpec.hs
> Quickfix action to prefix unused terms with '_'

- app/HieWrapper.hs
- app/MainHie.hs
- docs/Hacking.md
- docs/Protocol.md
- docs/hcar/2015.tex
- src/Haskell/Ide/Engine/Plugin/Base.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
Hello @alanz I'd like to join in and contribute to this project.
I made some simplifications and typo fixes while getting acquainted with the code base.
However I'm running into problem when running `make test`:
Some `LiquidSpec.hs` tests were failing, because I didn't have `liquid` binary (see TODO comment in this PR).
I didn't find any instructions in this project on how to set that up, so I followed the [install instructions of liquidhaskell](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md) but that didn't fix the tests (the output of the latest liquid binary didn't correspond to test expectations).
I'll be happy if you could assist me with making the tests work.
> Various simplifications

- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- test/functional/CompletionSpec.hs
resolves #367 
Modify completion so that the `forall a.` part of a simple
signature is stripped.
Higher ranked quantification, e.g. `(forall a. a -> a) -> Int`
isn't affected by this change.
Higher kinded types are also stripped e.g `forall (m :: * -> *).`
will be stripped.
One "edge case" of sorts are when types of multiple kinds are involved:
before, `return`, for example, was completed with:
```haskell
forall (m :: * -> *). Monad m => forall a. a -> m a
```
there's 2 quantifications there. With the somewhat naive way I've implemented forall stripping,
this becomes:
```haskell
Monad m => forall a. a -> m a
```
Should there have been 2 foralls in our completion in the first place?
Can we assume there will only ever be a situation with a single constraint arrow `=>` followed by a forall, …
> Strip forall when completing simple types

- Makefile
There were a few commands missing the stack-8.4.4.yaml, namely build-docs, test, 
build-copy-compiler-tool and icu-macos-fix-build.
> Add GHC 8.4.4 support to all commands

- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HaRe.hs
- src/Haskell/Ide/Engine/Plugin/HieExtras.hs
- test/functional/HaReSpec.hs
- test/unit/GhcModPluginSpec.hs
- test/unit/HaRePluginSpec.hs
- test/unit/JsonSpec.hs
Move `splitCaseCmd` from the GhcMod plugin to the HaRe plugin in order to avoid a circular dependency. 
Move the `casesplit`  tests to HaRe tests file. 
Add a `casesplit` CodeAction test.
I have created an associated [pull request](https://github.com/alanz/vscode-hie-server/pull/121) to avoid breaking vscode-hie-server use of `ghcmod:casesplit`.
closes: https://github.com/haskell/haskell-ide-engine/issues/907
> Make casesplit a HaRe action

- stack-8.4.4.yaml
- stack.yaml
Bring both the nightly and 8.4.4 stack files to lts12.17. Eventually the nightly will point to the 8.6.1 nightlies?
> Bump stack resolvers

- .gitmodules
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Plugin/Build.hs
- stack-8.2.1.yaml
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack.yaml
This PR just represents a cloneable repo that pulls in new-build supporting ghc-mod (https://github.com/alanz/ghc-mod/pull/14) and cabal-helper (https://github.com/alanz/cabal-helper/pull/2).
We modified `Build.hs` to use new-style commands but didn't find any behavioural changes in vscode with the haskell-language-server plugin nor emacs with the lsp-haskell package.
> submodule changes pointing to forks that support new-build

- Makefile
Builds and tars up all binaries into a tarball with the name based off of the tag + platform it was built on. Only tested on Darwin so far, can windows/linux people try this out?
> Add dist command to makefile

- README.md
I made a spacemacs layer and nix expression for those interested in spacemacs+hie+nix. It is the simplest thing that works rather than layering it on the haskell layer while I don't fully grok all the layers and interactions yet. This links it to the hie readme at @alanz 's request on irc.
May morph into a layer that can handle nix and non-nix hie project, get layered on the haskell layer or get merged into the official layer one day. Don't know which option is best yet, but it is a start! :slightly_smiling_face:
> Adding hie-nix instructions to readme.

- Makefile
> Install Cabal library using stack GHC

- README.md
`<foo>` doesn't get displayed in markdown so I wrapped it in `backticks`. Also clarified the language for installing GHC 8.0.2
> Clarifies installation instructions

- .travis.yml
The use of travis stages is so that we can stay in the allowed time limits for travis. Removed the testing part out of travis, since we have plenty tests already, but it can be added back with no problem.
> Use travis to generate MacOS binary releases

- README.md
This are some modifications based on the confusion/problems I hit with #997. 
* Fedora library installation instructions 
* Added a step to check GHC version before installing
* Handle each GHC version independently 
* Put the step to install all GHC versions at the end and with a warning for the installation size and time taken
> Updated README installation instructions

- .circleci/config.yml
- Makefile
- README.md
- build-all.ps1
- stack-8.6.3.yaml
- test/utils/TestUtils.hs
As stackage nightly from 2018-12-18 on supports it.
> Bring in GHC 8.6.3 support

- .gitignore
- README.md
- Shakefile.hs
- shake.yaml
Closes #650 
I implemented the Shakefile to be run directly from `stack`.
```
stack Shakefile.hs build-all
```
Features:
* `stack` is the only build requirement
* `shake` is used instead of `make`
* should work on all platforms (not fully tested yet)
* `dist` target works on windows out of the box, making it easier to create releases for windows
* submodules are synced / updated at the start -> works after clean clone of project
Quirks:
* `shake.yaml` is necessary to start the `stack Shakefile.hs ...` command before submodules are loaded.
* On first execution, a compiler is downloaded. However, no compiler is downloaded more than once.
Tested on: 
Working on NixOS with the following commands:
```bash
nix-shell -p "haskellPackages.ghcWithPackages (pkgs: with pkgs; [zlib tar shake])" zlib …
```
> Add Shakefile as possible build script

- app/HieWrapper.hs
- src/Haskell/Ide/Engine/Plugin/Base.hs
Closes alanz/vscode-hie-server#110
Closes #803
Sample log lines
```
2018-12-28 14:36:23.081677593 [ThreadId 4] - run entered for hie-wrapper(hie-wrapper) Version 0.4.0.1, Git revision 4f0c017 (dirty) (2286 commits) x86_64 ghc-8.6.3
2018-12-28 14:36:23.08184515 [ThreadId 4] - Current directory:/tmp/ff
2018-12-28 14:36:23.0846877 [ThreadId 4] - Cradle directory:/tmp/ff
2018-12-28 14:36:23.084807006 [ThreadId 4] - Using plain GHC version
2018-12-28 14:36:23.084980989 [ThreadId 4] - Project GHC version:No System GHC found
2018-12-28 14:36:23.085006736 [ThreadId 4] - hie exe candidates :["hie-No System GHC found","hie","hie"]
2018-12-28 14:36:23.085201395 [ThreadId 4] - found hie exe at:/home/alanz/.local/bin/hie
2018-12-28 14:36:23.085228858 [ThreadId 4] - …
```
>  hie-wrapper deals with missing System GHC

- README.md
Add troubleshooting note for missing gmp library on macOS
> Update README.md - workaround for missing gmp library

- Shakefile.hs
> Remove v1 prefix from cabal commands in Shakefile

- README.md
Some readme cleanup commits from #1035
p.s. for easier review - read commit diffs one by one
> Readme minor cleanup

- README.md
- install.hs
> Rename Shakefile.hs to install.hs

- README.md
The `--recursive` option is not listed in the [git-clone documentation](https://www.git-scm.com/docs/git-clone). It seems to have been renamed to `--recurse-submodules`. This commit changes the example `git clone` command in the readme to use the new option.
> Change --recursive to --recurse-submodules

- install.hs
The existing indention is uneven, and `runghc` isn't on its own line. I also removed the trailing whitespace.
> Fix install.hs stack comment formatting

- install.hs
While experimenting with `dist`, I noticed that submodules were not synced when the target `dist` was initially invoked.
Consequentially, cabal wasn't installed properly either. This is supposed to fix that.
Now after cloning the repo, invoking the target `dist` should be possible without an error.
> install.hs: Sync submodules and install cabal before building `dist`

- install.hs
- shake.yaml
closes #1049. This introduces an error message when a `stack build` fails from the `install.hs`. The error message suggests to call `stack clean` and retry the build.
It was necessary to upgrade to the latest version of `shake`
> Display error message on stack-compilation errors

- install.hs
Reduces number of places that need updates if a new GHC version is added. 
Generates the target help for `hie-*`.
Implements automatic alignment of target - message columns, so adding a new target with a longer name does not require to realign all column in the help message.
Also finishes documentation for `hieVersions`.
Functionality was not altered.
> Generate Shake help message based on GHC versions

- docs/Build.md
This PR adds a document to the `docs/` folder that discusses the motivation of the build script `install.hs`.
Comments are welcome
> Document design decision of build script `install.hs`

- Makefile
- README.md
- install.hs
Both `make help` and `./install.hs help` have not displayed a message for `build-doc-%`. 
I also noticed that the command name differs between make and shake (`build-doc-%` in make, `build-doc-hie-%` in shake). Is this intended?
> Show message for build-doc-% on make/shake help

- README.md
See individual commits for justification for throwing these paragraphs away.
The basic idea of a README should be to welcome new users and point them in the right direction. Droning on about old projects isn't really helping that goal.
> Remove some old cruft from README

- README.md
Clearly mention that `stack path --local-bin` must be on the path for the installation to work.
Closes #1095
> Update README, installation dir must be on path

- README.md
The function `lsp-haskell-enable` does not seem to exist anymore.
Per https://github.com/emacs-lsp/lsp-haskell the lsp-haskell mode should be enabled with `   (add-hook 'haskell-mode-hook #'lsp)`
> update the snippet for .spacemacs/user-config

- README.md
Links in TOC section describing installation are broken. I fixed the links, but I had to rename inner "Installation" section to "Installation with Shake" since there already exists "Installation" section (parent) and #installation link would wrongly refer to it.
> Fix table of contents (installation section) in README.md

- README.md
As further mitigation of #1008 after #1129 landed
> Update nightly in README to 8.6.4

- shake.yaml
Closes #1116.
Changes the resolver to avoid unregistering extra dep packages.
Pro:
Builds should now be idempotent, e.g. repeated invocation of `./install.hs build` should not build anything twice.
Con: 
Additional snapshot must be downloaded.
> Change resolver to achieve idempotent builds

- install.hs
As of #1136 we no longer need the nix config in `shake.yaml`.
> Remove redundant shake.yaml

- stack-8.6.3.yaml
Fixes issue #1131 
The documentation on Stackage for LTS 13.11 is incorrect. Stackage says it corresponds to GHC 8.6.3 but it actually corresponds to GHC 8.6.4: https://github.com/commercialhaskell/lts-haskell/blob/master/lts-13.11.yaml . LTS 13.10 is the last LTS release corresponding to GHC 8.6.3
> Use correct LTS version for GHC 8.6.3. Fixes #1131

- install.hs
Closes #1147 
Afaik, hoogle databases are located in `~/.hoogle`. 
Thus, if we invoke `hoogle generate` multiple times, we override the old database.
In the shake commands `cabal-build-all`, `build-all` we generate it multiple times.
As I understood it, we override all databases except the last one.
This change makes sure, shake installs hoogle and generates docs only once per command.
Also, shake now searches for the executable before installing it. If the executable is found, it is used to generate the hoogle database. Otherwise it is installed by either stack or cabal and then the database is generated. Executable is always installed into `.local/bin` or the respective path for Macos and Windows.
> Only generate hoogle database once

- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- test/functional/SymbolsSpec.hs
- test/testdata/Symbols.hs
Please don't merge as is, let's wait if alanz/haskell-lsp#143 gets merged.
The thing is that when used on modules that have pattern synonym declarations, hie kept crashing due to ```error``` call at line 693 of src/Haskell/Ide/Engine/Plugin/GhcMod.hs file. I have fixed this, but it required to introduce a new SymbolKind in ```haskell-lsp``` package.
This pull request reflects current state of things including referencing my forked version of ```haskell-lsp```. Once required changes to ```haskell-lsp``` get released, I'm going to update this pull request and remove my fork reference.
Meanwhile if there are problems with an approach I've taken, I have plenty of time to fix them.
> Support for Pattern Synonyms

- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
Related to #1143 
Also improves stability of hie, thus related to #1146 
If hlint chokes on anything, dont kill hie.
An error message might be desirable but I dont know how to do that.
> Prevent hie crash if hlint crashes

- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- src/Haskell/Ide/Engine/Plugin/Brittany.hs
- src/Haskell/Ide/Engine/Plugin/Floskell.hs
Especially the functions to load the config threw me off since it was not documented how they actually search for the config.
> Document formatters

- .gitmodules
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Support/HieExtras.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- stack-8.2.1.yaml
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack.yaml
- test/functional/TypeDefinitionSpec.hs
- test/testdata/gototest/src/Lib.hs
- test/testdata/gototest/src/Lib2.hs
- test/unit/HaRePluginSpec.hs
Closes #1010 
Missing:
Works for variables and sum type values.
Implement tests for `data`, `newtype` and `type`.
For type defs, the original type definition will be found.
If the data type definition is not in scope, empty result will be sent.
> Add ReqTypeDefinition to reactor

- hie-plugin-api/Haskell/Ide/Engine/Config.hs
- src/Haskell/Ide/Engine/LSP/Reactor.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- test/functional/DiagnosticsSpec.hs
- test/functional/FunctionalCodeActionsSpec.hs
- test/unit/JsonSpec.hs
This introduces a behaviour change in that hie will only run diagnostics on a file after it has been open and saved, unless the user hasn't manually configured the client to run diagnostics on chages.
I have found that running diagnostics as I type creates too much noise in my editor as more often than not I'm in a broken state. Additionally, this it makes HIE appear that it runs faster.
* Added the `diagnosticsOnChange` client config value
* Refactored the reactor a bit to not have hardcoded defaults smattered everywhere, which in some cases were inconsistent.
> Only run diagnostics onSave

- src/Haskell/Ide/Engine/Transport/LspStdio.hs
It works in VsCode with simple examples.
> Enable TypeDefinition Requests

- src/Haskell/Ide/Engine/Plugin/Hoogle.hs
> Document Hoogle Plugin

- cabal.project
- haskell-ide-engine.cabal
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/Haddock.hs
- src/Haskell/Ide/Engine/Plugin/Hoogle.hs
- src/Haskell/Ide/Engine/Plugin/Liquid.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- stack-8.2.1.yaml
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack.yaml
- test/functional/DeferredSpec.hs
- test/functional/HoverSpec.hs
The affects the `HoverReply` message.
All documentation is now returned in markdown, and it renders much better in `emacs-lsp`.
> Use LSP MarkupContent for generated documentation

- src/Haskell/Ide/Engine/Plugin/Hoogle.hs
Since the hoogle db location can be defined by the user, it may be possible that the database file location is wrong. 
If the file does not exist, an error is reported to the user, but if the file exists but it is just not a hoogle db, hoogle plugin crashes, taking hie with it.
This catches the error and wraps into a `HoggleError` that can be shown to the user, e.g. to tell him that the db is garbage.
Issue related to: #1146.
* ~[ ] Actually show an error to the user.~ Not adressed in this issue.
> Avoid crash in case of nonsensical hoogle db

- README.md
- install.hs
This pull-request is the result of my review of the `install.hs` file.
Following improvements were made:
* hoogle-database is only generated once. The same file was generated every time.
* `cabal-install` is not installed via `stack` if the executable `cabal` can already be found.
A review from @fendor has been conducted and the suggestions have been included.
> Build simplifications

- README.md
In https://github.com/haskell/haskell-ide-engine/commit/8fd5cba63213736e8720799a57afab32c8ef544b, the `build-docs` flag for install.hs was changed to `build-doc`, but was not updated in the README. I have added this change.
> Change 'build-docs' to 'build-doc' in README

- install.hs
The `install.hs` calls `cabal install Cabal-X`. This command was copied from the `Makefile` several months ago.
I have done exhaustive tests on different machies (linux only) and have not seen any effect of this line and `hie` works even without this command. This PR removes this command from the installation process.
Comments on this change and tests on MacOS and Windows are welcome!
> remove installation of Cabal by cabal

- src/Haskell/Ide/Engine/Plugin/Haddock.hs
> Make sure the end of formatted text is properly indicated

- README.md
It's been removed in NixOS/nixpkgs@d9b1486#diff-0190490bb2285cd4e5839b08cda4b00f
> README Nix - replace old.postFixup -> postFixup

- cabal.project
- haskell-ide-engine.cabal
This doesn't fix them all, but it gets us some way.
I'll make issues for the other things I've found.
> Fix some of the tests with cabal new-build

- haskell-ide-engine.cabal
Whilst we're doing #1194 @michaelpj
> Update build-tool-depends for func-test

- docs/Build.md
This PR updates the documentation of the build system based on the discussion in issue #1179. It documents the features of the `install.hs` script and the tradeoffs that have been made. Also, the changes of #1168 and #1184 have been documented.
Proof-reading and suggestions are welcome.
> expand documentation on the build system

- haskell-ide-engine.cabal
closes #1210 for now. This fixes the version of `lsp-test` to `0.5.1.1` instead of allowing `0.5.1.3`, which cause several errors.
In the long term, it will be necessary to upgrade `haskell-lsp` to version `0.10`, but this will be a longer process.
> fix version of lsp-test

- docs/Build.md
> Add documentation about building hie with profiling enabled. 

- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- test/testdata/ApplyRefactError.hs
- test/unit/ApplyRefactPluginSpec.hs
Fixes #451
Note: We need to catch `SomeException` because `applyRefactorings` throw an error by `error`.
> Prevent hie crash if apply-refact crashes

- install.hs
`stack install.hs cabal-build-doc`
was failing with:
```
cabal: Cannot build the package generate, it is not in this project (either directly or indirectly). If you want to add it to the project then edit the cabal.project file.
```
Looking at commit 8fd5cba63213736e8720799a57afab32c8ef544b it looks like a cut/paste error in `cabalBuildDoc` which this PR corrects.
> Extra argument causes cabal-build-doc to fail

- README.md
I noticed this error because I just upgraded my NixOS.
```
$ ~/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal2.4.1.0
zsh: no such file or directory: /home/infinisil/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal2.4.1.0
$ patchelf --print-interpreter ~/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal2.4.1.0
/nix/store/sw54ph775lw7b9g4hlfvpx6fmlvdy8qi-glibc-2.27/lib/ld-linux-x86-64.so.2
$ stat /nix/store/sw54ph775lw7b9g4hlfvpx6fmlvdy8qi-glibc-2.27/lib/ld-linux-x86-64.so.2
stat: cannot stat '/nix/store/sw54ph775lw7b9g4hlfvpx6fmlvdy8qi-glibc-2.27/lib/ld-linux-x86-64.so.2': No such file or directory
```
> Add Nix cabal-helper fix to troubleshooting section

- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- src/Haskell/Ide/Engine/Plugin/Brittany.hs
- src/Haskell/Ide/Engine/Plugin/Floskell.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- stack-8.2.1.yaml
- test/functional/FunctionalCodeActionsSpec.hs
- test/testdata/CodeActionImportList.hs
Closes #1086 
Offers code action to add a function to import list.
E.g. 
```haskell
foo = hPutStrLn stderr "Hello"
```
With 2 code actions this can be turned into:
```haskell
import System.IO (hPutStrLn, stderr)
foo = hPutStrLn stderr "Hello"
```
Requires:
> HsImport importlist

- hie-plugin-api/Haskell/Ide/Engine/ArtifactMap.hs
- hie-plugin-api/Haskell/Ide/Engine/Compat.hs
- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/TypeMap.hs
- hie-plugin-api/hie-plugin-api.cabal
- test/testdata/Types.hs
- test/unit/GhcModPluginSpec.hs
Under the orchestration of @mpickering, reimplements the `genTypeMap` function in a new module.
A Typechecked module is only traveresed once.
This reimplementation should have a lower memory footprint but is likely to increase the first startup time of modules.
Some parts may no longer have a type on hover.
Implementation has already been merged into #1126. There it is said to be working!
Closes #1156
> Typemap reimplementation

- .circleci/config.yml
- stack-8.6.5.yaml
And schedule circle CI for it, even though it is a repeat of the
nightly one.
Very pleasantly surprised to see that `install.hs` needs no change to
pick this up.
> Add an explicit stack file for GHC 8.6.5

- .gitmodules
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/LSP/CodeActions.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/Liquid.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- stack-8.2.1.yaml
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack.yaml
- test/functional/ProgressSpec.hs
Depends on a couple of tweaks with the VS code extension
> Add window/progress reporting for typechecking

- README.md
- Fix for Emacs document sync problems. I'm not sure what the actual cause is, but this is a workaround.
- Fix for emacs-direnv loading, see https://github.com/wbolster/emacs-direnv/issues/17 as well
> Troubleshooting for emacs

- .gitmodules
- cabal.project
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Support/HieExtras.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- stack-8.2.1.yaml
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
- It uses `rope-utf16-splay` instead of `yi-rope`
- Moving some functionality and types from `haskell-ide-engine` to `haskell-lsp`, to benefit other LSP servers based on it
- It is a step toward bringing in the `hie-bios` being worked on by @mpickering 
This is WIP pending merges of 
- https://github.com/alanz/haskell-lsp/pull/164
- https://github.com/alanz/lsp-test/tree/az-hie-bios
> Adapting to new haskell-lsp

- app/HieWrapper.hs
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/ArtifactMap.hs
- hie-plugin-api/Haskell/Ide/Engine/Context.hs
- hie-plugin-api/Haskell/Ide/Engine/Ghc.hs
- hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HaRe.hs
- src/Haskell/Ide/Engine/Plugin/Haddock.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Plugin/Package.hs
- src/Haskell/Ide/Engine/Scheduler.hs
- src/Haskell/Ide/Engine/Support/HieExtras.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- test/dispatcher/Main.hs
- test/unit/GhcModPluginSpec.hs
- test/unit/JsonSpec.hs
Since ghc-mod is going to be deprecated soon, and replaced by some new shiny thing as part of @DanielG 's GSOC, this patch attempts to help the process by slimming down and documenting the actual parts of ghc-mod currently used by hie.
> Narrow ghc mod core

- README.md
[hie-nix](https://github.com/domenkozar/hie-nix) has now been archived and superseded by [all-hies](https://github.com/Infinisil/all-hies).
> Change url for nix installation instructions

- install.hs
> Avoid legacy warning

- src/Haskell/Ide/Engine/Support/HieExtras.hs
- test/functional/CompletionSpec.hs
- test/testdata/completion/Completion.hs
closes #1259
* ~[ ] More Documentation~
> Support infix completions

- src/Haskell/Ide/Engine/Plugin/Hoogle.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- test/functional/FunctionalCodeActionsSpec.hs
- test/testdata/CodeActionImportListElaborate.hs
- test/unit/CodeActionsSpec.hs
Current implementation of the hsimport plugin can not deal with constructors, e.g. trying to import `Null` from `Data.Aeson` will wrongly try to import `Data.Aeson (Null)` instead of the correct `Data.Aeson (Value(Null))`. This pr aims to change that, while also preparing the implementation of #1191. 
Clones the API of HsImport with small adaptations for our use case, e.g. currently no support for qualified imports.
This pr also fixes the import of operators.
> Improve import action of hsimport

- haskell-ide-engine.cabal
- hie-plugin-api/hie-plugin-api.cabal
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
Tests failing, suspect a JSON encoding problem.
ping @cocreature, see the circle logs
Locally I get the first two of many failing tests, all with a spurious `<0>`
```
test/functional/FunctionalCodeActionsSpec.hs:557:9: 
1) FunctionalCodeActions, code actions, import suggestions, formats with brittany, Execute HsImport with formatter brittany, works with 3.8 code action kinds
expected: "Import module Control.Monad (when)"
but got: "Import module Control.Monad (<0>when)"
To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with brittany/Execute HsImport with formatter brittany/works with 3.8 code action kinds/"
test/functional/FunctionalCodeActionsSpec.hs:598:16: 
2) FunctionalCodeActions, code actions, import suggestions, formats with brittany, Execute …
```
> Trying out haskell-lsp 0.14

- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
This fixes UriCaches from being leaked via GhcModuleCaches. This is the result of 72 hours at ZuriHac between 3 people and a lot of time spent in gdb.
Fixes #412, #806, #665
Blog post coming soon
Co-Authored-By: Matthew Pickering <matthewtpickering@gmail.com>
Co-Authored-By: Daniel Gröber <dxld@darkboxed.org>
> Fix UriCaches being leaked

- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
* Actually the project cant be built in windows 7 due a bug in the package `unix-time` (via `hoogle` -> `wai-logger` -> `fast-logger`)
* The issue was resolved in the package: see https://github.com/kazu-yamamoto/unix-time/issues/51
* The first version of the package with the fix was `0.4.7`
This pr update the resolver for `stack-yaml` and `stack-8.6.5.yaml` to get one with the patched version and add `unix-time-0.4.7` as exta dependency for the rest of stack config files.
> Fix build for Windows 7

- install.hs
This PR extends the GHC search logic so that `install.hs` can find all available `ghc`s in `$PATH`.
The motivation is that at our company we have our own build of GHCs installed in some directories with custom versioning (e.g. `ghc-8.6.4.0`) and make them available by modifying `$PATH` variable. Currently `stack install.hs cabal-ghcs` cannot find them because it only tries to find GHCs whose version matches one of the versions returned by `getHieVersions`.
The new search logic does the following:
* Find all known GHCs in `$PATH`
* This is the original behavior.
* Find all available `ghc`s in `$PATH`
* Merge the two sets of paths.
* If stack-provided GHCs are included, exclude them.
* If both sets have the same version, the known GHC takes precedence.
This can also be useful to try `hie` …
> install.hs: Make all available GHCs in PATH buildable

- haskell-ide-engine.cabal
This makes sure PR #1304 is complete, constraining the cabal build as
well, for Windows 7
> Add unix-time constraint to cabal file

- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
closes https://github.com/haskell/haskell-ide-engine/issues/1296
> Fix a memory leak found by mpickering

- test/functional/FunctionalCodeActionsSpec.hs
It seems the message had become obsolete, the unique error case is the empty list.
I've added the list ot actions candidates to be run.
> Clear out pattern matching and error message of executeCodeActionByName

- src/Haskell/Ide/Engine/Plugin/Hoogle.hs
Reuses code.
Addresses one of the issues @jneira observed in https://github.com/haskell/haskell-ide-engine/issues/713#issuecomment-508656931.
Should fix any occurrence of `<0>` that was shown in Code actions for hsimport.
> Reuse unHTML for searchModules'

- stack-8.6.5.yaml
- stack.yaml
The version with the fix for windows 7 already is in both resolvers.
> Remove unnecesary extra-dep unix-time

- docs/Challenges.md
> Fix typos in Challenges.md

- README.md
The changes should make it easier for a newcomer to integrate HIE with Vim.
The previous version made me think that I as a Vim user had to clone the LanguageClient-neovim repo, when in reality vim-plug works just fine to install the plugin. Using vim-plug is arguably easier than cloning the repo and adding it to the runtime path.
> Clarify README.md for Vim users

- README.md
- docs/Build.md
Since b77e39beb1642abe75f8c4044819ba8e72792687, the `build-doc` goal got renamed into `build-data`. However the documentation is still referencing the old naming convention.
This PR updates the documentation in order to build the Hoogle database using the new `build-data` goal.
> Replace every occurrence of build-doc by build-data

- src/Haskell/Ide/Engine/Support/HieExtras.hs
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- test/functional/CompletionSpec.hs
- test/testdata/completion/Completion.hs
After @mpickering pointed this out yesterday, I noticed that completion was a lot more complicated than it needed to be. Instead of the convoluted wrangling we do with import declarations, all the information we need is in the `GlobalRdrEnv`.
In addition to this, I've separated out the step of getting the type information/snippets for the completion into the LSP `CompletionItemResolve` request. Type information for local variables which
is readily at hand in the `TypecheckedModule` itself is still reported in the original completion request.
A potential performance issue I've tried to fix is that looking up the types of all the possible completions would result in GHC loading a bunch of interface files it didn't need to.
For example, consider a module that imports `Prelude`, but doesn't …
> Simpler completion

- install/src/Stack.hs
Closes #1328. 
Is lifting the stack-version to 2.1.1 ok? Do we need still to support stack 1.9 ?
> lift required stack-version to 2.1.1

- .azure/linux-stack.yml
- .azure/macos-stack.yml
- .azure/windows-stack.yml
- .azure/windows.bashrc
* Azure has started recently to offer caching services as a preview:  https://docs.microsoft.com/en-us/azure/devops/pipelines/caching
* It has some warts affecting linux and macos builds:
* [Cached files lost their attributes](https://github.com/microsoft/azure-pipelines-tasks/issues/10841) inluding being executables so the cache cant be used out-of-the-box (ironically in windows works). I had to pack the directories in tar files to preserve its attrs..
* But tar files cant be cached directly [cause the `tar` utility sees them as directories although they are not](https://github.com/microsoft/azure-pipelines-tasks/issues/10925#issuecomment-513215241) (!!) .. so i had to put the tar files in a directory to keep them safe
When the first issue is corrected, the unix and macos config will be …
> Use preview of pipeline caching in azure builds

- install/src/Cabal.hs
this is one solution for #1327 
The installation fails if the `cabal` executable has an older version instead of re-installing a newer version
> fail installation if cabal-version is too low

- install/src/Cabal.hs
> Fix error message if outdated cabal dependency

- install/src/Help.hs
- install/src/HieInstall.hs
Fixes `stack-build` target which was broken if I executed the script with `cabal v2-run`
> Install: Fix broken stack-build target and fix cabal run help msg

- README.md
I used to use LCN, but have been using Coc for a long while now and it's better and for Neovim users it supports incremental sync which does not mess up hie's cached type information when you type. It's not perfect search and replace still does wipe Hie's cache between the first and last line changed, but the Neovim API resolution is supposed to get better eventually.
> Recommend Coc over LanguageClient-neovim

- README.md
While helping @AndrewNetwork debug their setup, this ended up being necessary to get rid of the error
A `cabal clean` was also done prior to that, but I don't think that was necessary, so I haven't included it here
> Readme: Mention cabal configure and restarting HIE for troubleshooting

- hie-plugin-api/Haskell/Ide/Engine/Compat.hs
- hie-plugin-api/Haskell/Ide/Engine/TypeMap.hs
- test/unit/GhcModPluginSpec.hs
Backported from https://github.com/mpickering/haskell-ide-engine/commit/13daf07124770a2643b63f8d581f88cacdea7ce1 by cherry-picking.
> Do not traverse into Generated bindings when creating TypeMap

- install/src/Cabal.hs
* Use `symlink-bindir` or `install-dir` depending on cabal version
* Add support for building in windows, using `install-method=copy`
* Use `v2-` prefix instead `new-` (available since `cabal-2.4.1.0`)
Fixes #1250
> Add support for building with cabal-3.0.0.0

- install/src/Cabal.hs
- install/src/HieInstall.hs
Stack should provide its own cabal, so I don't think the system cabal is
relevant here. This worked for me despite the check failing.
> Remove cabal check from stack builds

- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
*  Taking in account terms between backquote and single quote
* In my `hie.log` i'be observed that the quickfix request is
```
{
"jsonrpc": "2.0",
"id": 38,
"method": "textDocument/codeAction",
"params": {
"textDocument": {
"uri": "file:///d%3A/ws/haskell/haskell-ide-engine/test/testdata/CodeActionRename.hs"
},
"range": {
"start": {
"line": 0,
"character": 11
},
"end": {
"line": 0,
"character": 11
}
},
"context": {
"diagnostics": [
{
"range": {
"start": {
"line": 0,
"character": 7
},
"end": {
"line": 0,
"character": 15
}
},
"message": "* Variable not in scope: butStrLn :: [Char] -> t\n* Perhaps you meant `putStrLn' (imported from Prelude)",
"severity": 1,
"source": "ghcmod"
}
]
}
}
}
```
* So the suggestion `putStrLn` is between `` ` `` and `` ' `` instead `` ‘ `` and `` ’ `` (the …
> Fix code renaming in windows

- .azure/linux-stack.yml
- .azure/macos-stack.yml
- .azure/windows-stack.yml
* Azure builds are emitting warnings about the actual multiline cache key so it seems it is deprecated
> Use the new key format in one line for azure cache

- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Plugin/Package.hs
- src/Haskell/Ide/Engine/Support/HieExtras.hs
* Follow up of #1392 
* It turns out that there were more places where the code assumed ``‘`` and ``’`` as term delimiters
* And it assumed that the symbol to start a list option was `•` (in windows is `*`)
* It fixes almost all failed tests listed in #1391 (all except 11, 12 and 13) :smile: 
* The duplicated function `extractTerm` could be in common module but i am not sure where would be: maybe `Haskell.Ide.Engine.PluginUtils` in `hie-plugin-api`?
* An alternative impl for `extractTerm`would be `T.init $ T.tail $ T.dropWhileEnd (/= b) $ T.dropWhile (/= e)`, do you think that it would be better?
> Fix more code actions in windows

- test/functional/FunctionalCodeActionsSpec.hs
* More test fixes (the last ones!) taking in account windows specific delimiters
* This time they need to being added in tests themselves
* Fixes #1391
> Handling Windows specific delimiters in func tests

- haskell-ide-engine.cabal
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
- test/dispatcher/Main.hs
- test/functional/DeferredSpec.hs
- test/functional/DiagnosticsSpec.hs
- test/functional/FunctionalCodeActionsSpec.hs
- test/functional/FunctionalLiquidSpec.hs
- test/unit/ApplyRefactPluginSpec.hs
Bump haskell-lsp to 0.16
This is needed for GHC 8.8.1 support.
> Haskell lsp 0.16

- install/src/Cabal.hs
- install/src/Help.hs
- install/src/HieInstall.hs
* For stack users that want to install auto cabal with the required minimum version to work with hie
* As bonus, i've added some confirmation messages when installing cabal and when installing hie using cabal
> Add stack-install-cabal target and confirmation messages

- install/hie-install.cabal
- install/src/Cabal.hs
- install/src/HieInstall.hs
- install/src/Stack.hs
* We've found that the `cabal`executable used within `stack install.hs` executions after a first `stack install.hs stack-install-cabal` is the cached in `$STACK_ROOT/snapshots/{hash}/bin`. The cause is `stack` prepends that directory to the `$PATH` environment variable. That supposes:
* If you delete the cabal executable in `$PATH` after running `stack install.hs stack-install-cabal`, another invocation doesn't copy again the cabal executable, cause the version cached by stack is found. (thanks @jchia for detected it)
* All `stack install.hs cabal-*` use that cached version and no the original one, so if you upgrade your cabal in `$PATH` to `3.0.0.0` stack will continue using its cached version, (currently `2.4.1.0`)
* So in windows you could not use those goals
To avoid it i had to …
> Find and run cabal in user original $PATH

- README.md
... and update instructions to run the build script with cabal on windows
> Add instructions about install cabal with stack in the README

- .circleci/config.yml
- app/MainHie.hs
- test/functional/CompletionSpec.hs
- test/functional/DiagnosticsSpec.hs
- test/functional/HighlightSpec.hs
- test/functional/HoverSpec.hs
- test/functional/ProgressSpec.hs
- test/testdata/addPackageTest/cabal-exe/AddPackage.hs
- test/unit/PackagePluginSpec.hs
- test/utils/TestUtils.hs
On certain machines (such as mine), when stack executes the tests we get additional `window/ShowMessage` messages sent about loading a package environment.
Adjust the matchers in the tests to allow these to be there, without failing the tests.
> Robust tests

- haskell-ide-engine.cabal
- hie-plugin-api/hie-plugin-api.cabal
- stack-8.2.2.yaml
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
- test/functional/CommandSpec.hs
- test/functional/DeferredSpec.hs
- test/functional/FormatSpec.hs
- test/functional/FunctionalCodeActionsSpec.hs
- test/functional/ProgressSpec.hs
- test/unit/JsonSpec.hs
Together with haskell-lsp-types and lsp-test
This now supports LSP spec 3.15
> Update haskell-lsp to 0.17

- src/Haskell/Ide/Engine/Transport/LspStdio.hs
These need to be passed to haskell-lsp in order to declare it in the server capabilities.
> Register rename and implementation provider

- src/Haskell/Ide/Engine/Plugin/Liquid.hs
- test/unit/LiquidSpec.hs
We must run the liquid exe to generate results to be parsed.
> Make sure the liquid haskell test files are generated for unit-test

- install/src/Stack.hs
* If it is not set the fix makes no sense
* Fixes #1436
> Ignore the PATH fix if it is not set

- src/Haskell/Ide/Engine/Plugin/Liquid.hs
- test/dispatcher/Main.hs
- test/functional/FunctionalCodeActionsSpec.hs
- test/functional/FunctionalLiquidSpec.hs
- test/unit/LiquidSpec.hs
- test/utils/TestUtils.hs
This needs https://github.com/alanz/haskell-dockerfiles/pull/2 for CI,
to update the base image GHC and liquid haskell version.
> Adapt liquid haskell tests for version 0.8.6.2

- haskell-ide-engine.cabal
- test/unit/LiquidSpec.hs
Fixes #1443
I've hardcoded the liquid haskell version, not sure where i could put a constant with the value
> Unit test over the liquid haskell supported version

- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Transport/LspStdio.hs
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
Supersedes #1446 
@bubba has undertaken to provide a follow-up commit setting the newly structured `hieOptions` appropriately.
> Bump haskell-lsp et al to 0.18.0.0

- README.md
Some JSON parsing tools won't accept the last comma in an object.
> README.md > vim/coc setup > last comma in the json object doesn't parse.

- .azure/linux-installhs-stack.yml
- .azure/macos-installhs-stack.yml
- .azure/macos-stack.yml
- .azure/windows-installhs-stack.yml
- README.md
- docs/Build.md
- install.hs
- install/src/Cabal.hs
- install/src/Env.hs
- install/src/Help.hs
- install/src/HieInstall.hs
- install/src/Print.hs
- install/src/Stack.hs
* Improvements 
* ~~Use explicit list of ghc supported versions to filter out targets (stack and cabal).~~
* Use the list of stack-*.yaml files to filter out unsupported ghc versions of available ones.  Fixes #1445
* Add new target `build-lastest`to build hie with the lastest supported and available ghc
* *Change the default `build` target to build the lastest version and data files instead `build-all`*
* ~~Prints a warning about consumed resources and time when executing `build-all` and when printing the help~~
* Remove the `build-all` target (see https://github.com/haskell/haskell-ide-engine/pull/1452#discussion_r346941695)
* Bug fixes
* make `cabal-ghcs` work in windows
* fix the compiler used in the `cabal v2-install` phase of `cabal-hie-<version>`target
* fix the …
> Various improvements and fixes over shake install

- install/hie-install.cabal
- install/shake.yaml
* The new bounds of shake let install it with all supported resolvers of hie so if users want to change `shake.yaml` to match the resolver of hie itself they will be able to do it
* I still have kept the upper bound cause a new release of shake could break the script
* I've changed the actual resolver to match the latest hie cause i think it will be the most common scenario and this way run the script and install hie will use the same ghc.
* Tested with all `stack-*.yaml` resolvers and `lts-14.14`
* Fixes #1460
> Relax bounds of shake and use latest hie resolver

- README.md
Spacemacs now officially supports HIE. I updated the README.
> Update the instructions for Spacemacs

- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
Bump hlint to 2.2.4, floskell to 0.10.2, and GHC 8.6.5 resolver to lts-14.16
> Bump versions

- test/functional/FunctionalCodeActionsSpec.hs
- test/unit/LiquidSpec.hs
- Relax liquid version check
- Reenable `noDiagnostic` assertions
> Some tidying up for tests

- README.md
libtinfo-dev has been replaced by libncurses-dev since Ubuntu 18.10
> Update Ubuntu dependency

- .gitmodules
- cabal.project
- hie-plugin-api/Haskell/Ide/Engine/Ghc.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginApi.hs
- hie-plugin-api/hie-plugin-api.cabal
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
They are only used for the GHC module graph, which is currently not
generated in any useful way, so not used.
Closes #1486
>  Remove ghc-project-types

- src/Haskell/Ide/Engine/Options.hs
PR #1489 removed the `--lsp` option, resulting in a hard failure if a
client uses it to start up the server.
Parse it, but ignore it, as an interim measure.
> Retain the --lsp option, to not break existing clients

- hie-plugin-api/Haskell/Ide/Engine/MonadFunctions.hs
Hi!
In `MonadFunctions.hs` the function `errorm` lifts a `warningM` in its implementation, as opposed to `errorM` which seems more appropriate. Maybe there is a reason for it or it is a slip?
@fendor
> Make errorm use errorM instead of warningM

- app/MainHie.hs
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Plugin/GhcMod.hs
- test/unit/GhcModPluginSpec.hs
Certain hie clients expect to be able to executeCommand the ghmod
plugin commands.
Make them available under the "ghcmod" name, routed to the new "generic"
plugin.
> Restore the ghcmod plugin command routing

- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Scheduler.hs
- src/Haskell/Ide/Engine/Server.hs
- src/Haskell/Ide/Engine/Version.hs
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
- test/dispatcher/Main.hs
- test/functional/HieBiosSpec.hs
- test/plugin-dispatcher/Main.hs
- test/unit/ApplyRefactPluginSpec.hs
- test/unit/ContextSpec.hs
- test/unit/ExtensibleStateSpec.hs
- test/unit/GenericPluginSpec.hs
- test/unit/HooglePluginSpec.hs
- test/unit/PackagePluginSpec.hs
- test/utils/TestUtils.hs
Fixes #1495 
Finds the libdir directory of the appropriate ghc version at run-time. 
Introduces the `isCabalCradle` predicate to complement the `isStackCradle`
While it works in manual test-cases I have the following considerations:
* Cradle initialisation happens in too many places. At least the one in "NotInitialized" can be skipped, imo.
* We might select the wrong ghc version in certain circumstances.
* I dont know what happens if the system lib dir is `Nothing`
> Find the libdir directory of ghc at run-time

- test/unit/GhcModPluginSpec.hs
This missed CI as it came in from #1505
> Adapt GhcModPluginSpec after merge of #1496

- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- src/Haskell/Ide/Engine/Scheduler.hs
- src/Haskell/Ide/Engine/Server.hs
- test/dispatcher/Main.hs
- test/plugin-dispatcher/Main.hs
- test/utils/TestUtils.hs
Now that its not possible to *not* have LspFuncs since the only transport is LSP
> Change Maybe LspFuncs to LspFuncs inside IdeEnv

- .gitignore
- README.md
- hie.yaml.cbl
- hie.yaml.stack
The cabal one is tested per component.
The stack one has issues because of the nested library.
Note: the suffix on the cabal one cannot be '.cabal', as that
extension is already used.
> Add sample hie.yaml files for stack and cabal

- hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
Fixes #1530 
Behaviour changed because of https://github.com/DanielG/cabal-helper/pull/84
cc  @bubba
> Look for stack.yaml before selecting .cabal location as project root

- src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
> Return hlint code actions as type 'quickfix'

- app/MainHie.hs
- cabal.project
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Options.hs
- test/utils/TestUtils.hs
Closes #1412 
Example output
```
Running HIE(hie)
Version 1.0.0.0, Git revision 666626ede0e0bf5f1c876bd04f2a8a0cc68e7bb1 (dirty) (3534 commits) x86_64 ghc-8.6.5
Current directory:/home/alanz/mysrc/github/alanz/haskell-ide-engine/app
args:[]
Looking for project config cradle...
2020-01-01 22:41:46.396914848 [ThreadId 4] - Cabal-Helper dirs: ["/home/alanz/mysrc/github/alanz/haskell-ide-engine","/home/alanz/mysrc/github/alanz/haskell-ide-engine/app/File.hs"]
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following would be built (use -v for more details):
- hie-plugin-api-0.14.0.0 (lib) (configuration changed)
- haskell-ide-engine-1.0.0.0 (lib) (configuration changed)
- haskell-ide-engine-1.0.0.0 (test:wrapper-test) (configuration changed)
- …
```
> First pass at printing out debug info if started without --lsp

- README.md
- cabal-hie-install
- cabal-hie-install.cmd
- cabal-install.cmd
Sorry for restore an os specific script but i've got tired of typing or copypasting it
> Add cmd script to install with cabal

- hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Scheduler.hs
- src/Haskell/Ide/Engine/Server.hs
- test/dispatcher/Main.hs
- test/plugin-dispatcher/Main.hs
Fixes #1509
Improves amount of information the error message gives.
Also aims to give: possible solutions, and teaching material.
> Improve quality and information density of error message

- hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
Closes #1550 
No `*.cabal`, `cabal.project`, `stack.yaml` or `hie.yaml` must be in any of the ancestor directories of the file to open. Does not support any packages.
> Fallback to direct cradle if no project context can be found

- README.md
Adds --lsp flag to integration instructions for vim+coc and vim+languageclient
Part of #1558
> Readme lsp flag

- install/src/HieInstall.hs
cabal install works different than cabal build
and does not re-use its artifacts. Even some
dependencies may be rebuilt.
Future cabal versions may fix that, we don't know.
> Avoid building HIE twice

- .azure/linux-installhs-stack.yml
- .azure/windows-installhs-stack.yml
- README.md
- docs/Build.md
- install/hie-install.cabal
- install/src/Cabal.hs
- install/src/Help.hs
- install/src/HieInstall.hs
- install/src/Stack.hs
> Don't mix stack with cabal

- .azure/linux-installhs-stack.yml
- .azure/linux-stack.yml
- .azure/macos-installhs-stack.yml
- .azure/macos-stack.yml
- .azure/windows-installhs-cabal.yml
- .azure/windows-installhs-stack.yml
- .azure/windows-stack.yml
- azure-pipelines.yml
* It makes release for all jobs (total 24), example: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=371&view=artifacts&type=publishedArtifacts
* It fixes the z3 installation for macos
* It adds the hoogle databse generation, needed for tests
* It fixes the cache for windows, make it like the unix and macos ones
* I've open an issue upstream: https://github.com/microsoft/azure-pipelines-tasks/issues/12070
* I've make some advancesin the task that uses cabal to run the install.hs script but it still fails trying to install hie
* It adds specific triggers
The history is a liitle bit hairy, maybe it should be squashed.
> Enable azure releases and some fixes

- README.md
> Mention hlint data file handling in readme

- app/MainHie.hs
- app/RunTest.hs
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Options.hs
Extends PR #1538 
<details>
<summary>
Whole log run (this is huge)
</summary>
```
Running HIE(hie)
Version 1.0.0.0 x86_64 ghc-8.6.5
To run as a LSP server on stdio, provide the '--lsp' argument
Current directory:/home/baldr/Documents/haskell/fprog
args:["--debug"]
Looking for project config cradle...
2020-01-10 18:58:28.457769468 [ThreadId 4] - Cabal-Helper found these projects: ["ProjLocV2File {plCabalProjectFile = \"/home/baldr/Documents/haskell/fprog/cabal.project\", plProjectDirV2 = \"/home/baldr/Documents/haskell/fprog\"}","ProjLocStackYaml {plStackYaml = \"/home/baldr/Documents/haskell/fprog/stack.yaml\"}","ProjLocV2Dir {plProjectDirV2 = \"/home/baldr/Documents/haskell/fprog\"}","ProjLocV1Dir {plProjectDirV1 = \"/home/baldr/Documents/haskell/fprog\"}"]
2020-01-10 18:58:28.550718757 …
```
> Load all possible haskell source files

- app/MainHie.hs
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Plugin/Ormolu.hs
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
- test/functional/FormatSpec.hs
- test/functional/FunctionalCodeActionsSpec.hs
Hi! This addresses https://github.com/haskell/haskell-ide-engine/issues/1410 for the [Ormolu formatter](https://hackage.haskell.org/package/ormolu)
I still have some work to do, that is sending a warning if the Format Selection option is used (in lines 31-33 of the committed `Ormolu.hs`), as this function is [not yet supported by Ormolu](https://github.com/tweag/ormolu/issues/480#issuecomment-562966292), but I don't know exactly the best way to proceed. I was pointed to `LspStdio.hs` and about throwing a warning on the right thread, but I'm still interpreting the file and how to make use of the functions in it.
Feel free to provide any suggestions.
Also, I think I should put up some tests in `FormatSpec.hs` when `Ormolu.hs` is done, to let everyone check that everything works 😃
> Ormolu formatter support

- cabal.project
Fixes building via cabal with ghc-8.8 until ormolu bumps its dependencies
> Allow newer optparse-applicative for ormolu

- stack-8.8.1.yaml
- test/functional/FormatSpec.hs
* Follow up of #1583
* Temporary workaround until #1579 (or upstream fix) is merged
> Allow newer optparse-applicative for ormolu (stack version)

- cabal.project
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Plugin/Ormolu.hs
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.1.yaml
- stack-8.6.2.yaml
- stack-8.6.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.1.yaml
- stack.yaml
hlint 2.2.8 embeds its config file, making redistribution easier.
Closes #1587
> Update hlint to 2.2.8 and ormolu to 0.0.3

- haskell-ide-engine.cabal
- test/functional/FunctionalCodeActionsSpec.hs
- test/testdata/CodeActionImportListElaborate.hs
- test/unit/HsImportSpec.hs
- test/utils/TestUtils.hs
Previously, we had long running func-tests for HsImport.
However, after the first code-action tests, we actually are
testing the same functionality over and over again.
Moreover, we dont have to test that HsImport works as intended
since they have a huge set of tests, anyways.
Now, we only test that our implementation of the plugin
truly maps correctly to HsImport, accelerating execution time
of func-tests as a side-effect. Hooray!
Part of #1585
> Demote HsImport func-tests to unit-test

- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
- test/testdata/cabal-helper/implicit-exe/implicit-exe.cabal
- test/testdata/cabal-helper/mono-repo/A/A.cabal
- test/testdata/cabal-helper/mono-repo/B/B.cabal
- test/testdata/cabal-helper/mono-repo/C/C.cabal
- test/testdata/cabal-helper/multi-source-dirs/Setup.hs
- test/testdata/cabal-helper/multi-source-dirs/multi-source-dirs.cabal
- test/testdata/cabal-helper/multi-source-dirs/src/BetterLib.hs
- test/testdata/cabal-helper/multi-source-dirs/src/input/Lib.hs
- test/testdata/cabal-helper/simple-cabal/simple-cabal-test.cabal
- test/testdata/cabal-helper/simple-stack/simple-stack-test.cabal
- test/testdata/cabal-helper/sub-package/plugins-api/plugins-api.cabal
- test/testdata/cabal-helper/sub-package/sub-package.cabal
- test/unit/CabalHelperSpec.hs
> Fix multi source directories

- cabal.project
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- src/Haskell/Ide/Engine/Plugin/Ormolu.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.1.yaml
- stack.yaml
> Pass Ormolu cradle flags & default-extensions

- hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
- src/Haskell/Ide/Engine/Plugin/HsImport.hs
- src/Haskell/Ide/Engine/Support/HieExtras.hs
- src/Haskell/Ide/Engine/Support/Hoogle.hs
Fix error message parsing to enable HsImport plugin to import Types.
Moreover, fix generation of Code Actions to avoid cases
where the same Code Action was displayed multiple times.
Overall tests for HsImport actions are lacking. This problem flew under the radar since I initially wrote the feature of import-lists.
> Fix error message parsing to import types

- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- hie-plugin-api/Haskell/Ide/Engine/TypeMap.hs
There were few functions with some constraints that were
redundant. Those constraints got removed.
> Remove compiler warnings

- src/Haskell/Ide/Engine/Plugin/Ormolu.hs
This is a bit of a hack but it works pretty great.
We format lines of equal or increasing indention, not precise ranges, and there are a few documented edge cases.
> Ormolu range format support

- README.md
Corrections to improve my quirky english are very welcome :sweat_smile:
> Mention the new haskell-ide in the README

- app/HieWrapper.hs
- app/MainHie.hs
- src/Haskell/Ide/Engine/Options.hs
Not sure how to merge the CPP'd imports.
Note that hie-wrapper now partakes of the hSetBuffer stderr LineBuffering
and the "hie-bios".
> Deduplicate main for hie/hie-wrapper

- install/src/Cabal.hs
- install/src/Help.hs
- install/src/HieInstall.hs
- install/src/Stack.hs
To build hie with the default `stack.yaml` file
I've not added it to documentation cause its user will be developers
Closes #1565
> Add dev target to stack install.hs

- .azure/windows-cabal.bashrc
- .azure/windows-cabal.yml
Moving cabal root dir from `%APPDATA%\cabal` to `D:\cabal` and free space in C:
They are about to increase its capacity but this could be kept afterwards
> Azure fix win cabal 8.4.4

- .gitmodules
- app/MainHie.hs
- cabal.project
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/ArtifactMap.hs
- hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
- hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/Logger.hs
- hie-plugin-api/Haskell/Ide/Engine/ModuleCache.hs
- hie-plugin-api/Haskell/Ide/Engine/MonadFunctions.hs
- hie-plugin-api/hie-plugin-api.cabal
- src/Haskell/Ide/Engine/Scheduler.hs
- src/Haskell/Ide/Engine/Version.hs
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.1.yaml
- stack-8.8.2.yaml
- stack.yaml
- test/functional/ProgressSpec.hs
- test/unit/CabalHelperSpec.hs
- test/unit/GenericPluginSpec.hs
Closes https://github.com/haskell/haskell-ide-engine/issues/1490
> Update HIE to use latest hie-bios

- .azure/windows-stack.yml
- cabal.project
- install/src/HieInstall.hs
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.1.yaml
- stack-8.8.2.yaml
- stack.yaml
cabal now index state 2020-01-31T21:11:24Z
GHC 8.8.2 is nightly-2020-01-31
GHC 8.6.5 is lts-14.22
hlint is 2.2.9
brittany is 0.12.1.1
> Bump resolvers, hlint, brittany

- .azure/windows-cabal.bashrc
- .azure/windows-cabal.yml
- .azure/windows-installhs-cabal.yml
I forgot to unpack the cache in the correct drive
> Fix cabal-hie-install in windows azure ci

- azure-pipelines.yml
Prs modifying docs continued to trigger the azure builds
> Azure: not trigger pr builds by path

- install/src/Cabal.hs
- install/src/Env.hs
- install/src/HieInstall.hs
* It throws an error if there is no one 
```console
D:\ws\haskell\haskell-ide-engine>cabal v2-run .\install.hs -w D:\bin\ghc-8.6.5\bin\ghc  --project-file=install\shake.project
........
********************************************************************************
No ghc installations found in $PATH.
The script requires at least one ghc in $PATH to be able to build hie.
********************************************************************************
No ghc installations found in $PATH.
The script requires at least one ghc in $PATH to be able to build hie.
CallStack (from HasCallStack):
error, called at src\Env.hs:79:3 in hie-install-0.8.0.0-inplace:Env
```
Closes #1620
> Install script with cabal: check there is one ghc in $PATH 

- cabal.project
- haskell-ide-engine.cabal
- hie-plugin-api/Haskell/Ide/Engine/Ghc.hs
- hie-plugin-api/hie-plugin-api.cabal
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.1.yaml
- stack-8.8.2.yaml
- stack.yaml
* Bumping up in build config files
* A minor change due to the new type definition of `NormalizedUri`
* Closes #1643 and fixes #1560 (this time for real)
> Use haskell-lsp-0.20

- hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
Oversight of original implementation, caught by @jneira 
cc @jneira
> Set current working directory when executing project ghc

- .azure/windows-cabal.bashrc
- .azure/windows-cabal.yml
- .azure/windows-installhs-cabal.yml
- .azure/windows-installhs-stack.yml
- .azure/windows-stack.bashrc
- .azure/windows-stack.yml
- cabal.project
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.1.yaml
- stack-8.8.2.yaml
- stack.yaml
* Using a patched version of cabal-helper (until the next release)
* It includes the remove of the private lib
* Azure windows agent have changed their drives space now `C:` has lot of more space than `D:`, so i've switched again cache to `C:`
* Some of unit failing tests had been fixed by #1654
> Fix failing tests in windows (reloaded)

- .azure/macos-stack.yml
...by brute force :disappointed:
> Azure: try to generate hoogle twice to avoid 403 http errors for macos

- README.md
Hi!
I'd like to offer two improvements to the installation instructions for Arch Linux:
* Typo fixes
* Add hint to reduce the number of supported GHC versions thus speeding up HIE compilation
> Fix typos in README. Add hint to speed up HIE compilation

- hie-plugin-api/Haskell/Ide/Engine/GhcUtils.hs
Previously it was displayed as a value from 0% to 1%
As specified https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workDoneProgress
See also https://github.com/alanz/haskell-lsp/blob/1f85ef3c150dc8b2626a181c47d8635015e67ee5/src/Language/Haskell/LSP/Core.hs#L150-L154
> Report progress as a percentage

- app/MainHie.hs
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Options.hs
- test/unit/OptionsSpec.hs
I extracted mode-specific `GlobalOpts` fields into separate types, updated the parsing logic to handle new types as an alternative and updated the places where `GlobalOpts` were used.
Added unit tests for option parser exposed by `Haskell.Ide.Engine.Options`.
> Fix #1578 - Redesign option parsing for main executable

- hie-plugin-api/Haskell/Ide/Engine/GhcModuleCache.hs
`cabal haddock lib:hie-plugin-api` succeeds now.
Closes #1693 
@mouse07410 can you check if this fixes the error?
> Fix: haddock for hie-plugin-api

- .azure/macos-installhs-cabal.yml
- haskell-ide-engine.cabal
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.1.yaml
- stack-8.8.2.yaml
- stack.yaml
- test/unit/OptionsSpec.hs
* `@revn` way to specify a revision in `stack.yaml` files seems to be not reliable: it is using the package version without the revision under some circumstances. It is possible that wipping out the entire `$STACK_ROOT` could fix it but is is not desirable
* we have [tested ](https://github.com/haskell/haskell-ide-engine/issues/1689#issuecomment-597922927) that using pantry sha seems to make stack use the patched version, although it is somewhat ugly
* closes #1689
> Use sha instead revision for hsimport and other fixes

- cabal.project
- cabal.project-8.8.2
- hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
- hie-plugin-api/hie-plugin-api.cabal
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.1.yaml
- stack-8.8.2.yaml
- stack.yaml
> Update hie-plugin-api to use unliftio-core 0.2.0.1

- test/functional/FormatSpec.hs
- test/testdata/Format.hs
Show how different formatters are formatting code with a data type definition
> Extend FormatSpec with a data types

- install/shake.yaml
* To avoid a bug in windows of previous unix-time versions
* It is throwed with stack executions within the `install.hs` script using `./install/shake.yaml` config
* Fixes #1714
> Make install script use unix-time-0.4.7

- src/Haskell/Ide/Engine/Plugin/Haddock.hs
> Haddock source file names may use either dot or dash as separator

- hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
> Strip RTS flags, since we cant honor them

- .azure/linux-stack.bashrc
- .azure/linux-stack.yml
* To avoid download it again and not waste disk space
* Fixes #1729 
* The builds are failing due to timeouts when executing `stack exec hoogle generate`: see https://github.com/ndmitchell/hoogle/issues/347
> Use installed ghc in stack linux builds

- README.md
The `hie` command needs to include the `--lsp` parameter for it to work as an LSP server.
> Update Sublime Text HIE command

- hie-plugin-api/Haskell/Ide/Engine/Cradle.hs
Closes #1640
Currently, hie-wrapper uses the cradle type to find the ghc version to
use on the project. Cabal-Helper does not only return the cradle type
but also initialises the packages of the project, which may take a long
time since it starts building dependencies. Moreover, it causes
hie-wrapper to take way longer than necessary to find the project type,
and thus, the ghc version to use on the project.
This violates the isolation of the cradle, some work happens before
loading the options for a filepath, some during it.
This commit unifies the behaviour with hie-bios:
* All the work happens during loading the options for the given
filepath.
It speeds up the initial start-up of hie if users use the implicit
cradle discovery mechanism.
It makes the implementation a bit less hacky. …
> Move finding the package for a filepath

- cabal.project
- haskell-ide-engine.cabal
- stack-8.8.3.yaml
- stack.yaml
cabal to 2020-05-02T10:11:15Z
stack-8.8.3 to lts-15.10
stack to nightly-2020-05-01
> Bump resolvers

- stack-8.8.3.yaml
See also https://github.com/haskell/haskell-ide-engine/pull/1694#issuecomment-627456134
Ping @jneira @fendor @gdziadkiewicz
> Fix stack.yaml syntax for a specific revision

- cabal.project
- haskell-ide-engine.cabal
- src/Haskell/Ide/Engine/Plugin/Package.hs
- stack-8.4.2.yaml
- stack-8.4.3.yaml
- stack-8.4.4.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
* Closes #1758 
* It has needed:
* Use Cabal-3.0.1.0 in all build plans, cause cabal-helper requires it for windows, to avoid a bug in previous versions (for windows)
* To being able to use it we had to request revisions for haddock-api, see https://github.com/DanielG/cabal-helper/issues/116. We are using them in stack.yaml's
* Other packages has been upgraded, to get versions compatibles with Cabal-3.0.2.0
* There were some conditions over Cabal api changes using the ghc version instead, the code failed when changing the cabal version and now it is more correct
> Use cabal-helper 1.1

- README.md
The `settings.json` sample is not valid JSON, it's more of a JSON schema.  Using JSON highlighting causes github to (un)helpfully highlights the "errors".
Also fix a minor grammar mistake.
> README.md: Change display of settings.json sample

- cabal.project-8.6.5
* To woraround a cabal bug that makes the target `./cabal-hie-install hie-8.6.5` fail if the user has the docs generation enabled in cabal global config
* Closes #1741
> Avoid building docs for haddock-api + cabal + ghc-8.6.5

- README.md
- hie-plugin-api/Haskell/Ide/Engine/Config.hs
- test/functional/CompletionSpec.hs
- test/functional/FormatSpec.hs
Brings it inline with other language servers, and also fixes it with vscode-hie-server 0.1.
A breaking change for people's configurations, but the ship has already sailed on vscode-hie-server, whoops!
> Rename configuration section languageServerHaskell => haskell
